export const en = {
	seo: {
		home: {
			title: 'Dosimex — Professional Radiation Protection Software',
			description: 'Dosimex: 17 professional tools for radiation protection. Gamma, beta, neutron dose calculations, internal exposure and atmospheric transfer.',
		},
		software: {
			title: 'Calculation Tools — Dosimex',
			description: 'Explore 17 Dosimex tools: operational codes (gamma, beta, neutron), interactive learning modules and measurement utilities for radiation protection.',
		},
		product: {
			title: 'Product & Pricing — Dosimex',
			description: 'Dosimex 3.2 + Dosismart pack: 17 calculation codes, single-user license from €500/year excl. VAT. 14-day free Dosismart trial, no commitment.',
		},
		training: {
			title: 'Radiation Protection Training — Dosimex',
			description: 'Dosimex in-house training from 1 to 3 days: hands-on calculation tools, practical exercises applied to real radiation protection cases.',
		},
		books: {
			title: 'Recommended Readings — Dosimex',
			description: 'Curated selection of reference books on radiation protection, dosimetry and nuclear physics recommended by Dosimex experts.',
		},
		manuals: {
			title: 'Documentation & Validation — Dosimex',
			description: 'User manuals, MCNP validation files and internship reports for Dosimex-GX. Complete documentation available as downloadable PDFs.',
		},
		videos: {
			title: 'Videos & Tutorials — Dosimex',
			description: 'Explanatory videos for each Dosimex tool: operational, learning and measurement packs. Visit our YouTube channel for more.',
		},
		about: {
			title: 'Our Team — Dosimex',
			description: 'Meet Gérald Lopez and Alain Vivier, the creators of Dosimex. Over 30 years of experience in radiation protection and dosimetry.',
		},
		contact: {
			title: 'Contact & Quote — Dosimex',
			description: 'Contact Dosimex for a quote, demo or free Dosismart trial. Video conference demonstration available.',
		},
		blog: {
			title: 'Blog — Dosimex',
			description: 'Articles and news on radiation protection, dosimetry and Dosimex tools.',
		},
		legal: {
			title: 'Legal Notice — Dosimex',
			description: 'Legal notice for dosimex.fr: publisher, hosting, terms of use, intellectual property and personal data.',
		},
		testimonials: {
			title: 'User Feedback — Dosimex',
			description: 'Discover feedback from Dosimex users: IRSN, EDF, ORANO, CNRS, university hospitals and other radiation protection professionals share their experience.',
		},
	},
	altText: {
		logo: 'DOSIMEX - Radiation Dosimetry Software',
		flagUk: 'UK flag - DOSIMEX available in English',
		decorativePattern: 'Decorative geometric pattern background',
		radiationSymbol: 'DOSIMEX radiation safety symbol - clover leaf icon',
		carouselMain: 'DOSIMEX radiation dosimetry software interface mockup',
		carouselScreens: 'Banner image',
		trainingMaterials: 'DOSIMEX radiation safety training course materials',
		manualCover: 'Manual cover',
		cardIcon: 'Icon',
	},
	navbar: {
		items: ['Software', 'Training', 'Documentation', 'About', 'Contact', 'Blog'],
		button: 'Free Dosismart trial 14 days',
	},
	home: {
		hero: {
			title: 'Master your radiation protection calculations',
			badge: 'New: Dosismart, gamma calculation in the browser',
			subtitle:
				'A set of practical, easy-to-use, validated calculation tools that address many situations encountered in radiation protection. They will allow you to improve your expertise level.',
			cta: 'Discover the tools',
			trialButton: 'Training courses',
			priceNote: 'From €500/year excl. VAT — Free Dosismart trial',
		},
		partners: {
			title: 'Partners',
			descriptions: [
				'A company that loves projects. So do we',
				'The first to use Dosimex in PCR training',
				'Partner for radiation protection training and Dosimex user',
				'The only ones in France who know how to encrypt Excel (and other Microsoft products). Without them we simply would not exist',
				'We are proud to help them in their missions',
				'Our historical editor for the book "calculation of doses generated by ionizing radiation"',
				'Use Dosimex a lot in their calculations',
				'Among the first to support us. And they continue to do so. Thank you',
				'Our long-time partner for training in gamma spectrometry and other fields',
				'They have honored us with their appreciation of our codes. And we highly recommend the RayXpert code',
			],
		},
		offers: {
			title: 'What you get',
			description:
				'17 tools covering the essentials of radiation protection. Each code comes with an explanatory video and downloadable validation files.',
			card1: {
				title: 'Dosimex',
				description:
					'17 calculation tools in Excel: gamma, beta, neutron, internal exposure, radiography, educational modules and measurement utilities.',
				linkLabel: 'See the tools',
			},
			card2: {
				title: 'Dosismart',
				description:
					'Your calculations in the browser. Point source gamma available now. 3D sources and X-ray generator under development.',
				linkLabel: 'Try for free',
			},
			card3: {
				title: 'Training',
				description:
					'Hands-on training adapted to your specific use cases and radiation protection problems.',
				linkLabel: 'Learn more',
			},
		},
		dosismart: {
			title: 'Dosismart — your calculations in the browser',
			text: 'The web application making radiation protection calculations accessible anywhere. No installation, any OS, any device.',
			available: 'Available now: point source gamma calculation.',
			coming: 'Coming soon: 3D sources and X-ray generator.',
			button: 'Try for free',
		},
		close: {
			title: 'Get Dosimex',
			price: 'Dosimex: from \u20AC500/year excl. VAT',
			includes: '17 Excel tools + Dosismart access + technical support',
			dosismartNote: 'Dosismart is also available as a free trial',
			quoteButton: 'Request a quote',
			trialButton: 'Try Dosismart',
		},
		packs: {
			title: 'What Dosimex contains',
			subtitle: 'Every code is validated (MCNP, RayXpert, Microshield) with full documentation included. The pack also includes 11 course documents.',
			allTools: 'See all tools in detail',
		},
		numbers: {
			items: [
				{ value: '+30 years', label: 'of experience' },
				{ value: '+1500', label: 'users in the field' },
				{ value: '17', label: 'calculation codes' },
			],
		},
		videoTitle: 'Dosimex Presentation',
		videos: {
			title: 'Join us on YouTube',
			description:
				'We offer you other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Our YouTube channel',
		},
		opinion: {
			name: 'Jean-Lionel Trolet',
			job: 'EAMEA — French Military School of Nuclear Energy Applications',
			text: 'I use DOSIMEX, which gives me total satisfaction, both by the quality of its results and its ease of use, in the training of personnel from the Ministry of the Armed Forces. It has, among other things, the strength of taking into account common situations faced by MinArm agents, both in the roles of medical PCRs (thanks to the X-ray calculation module!) as well as those involved at all levels in the industrial field (from PNR to engineer). Finally, it is so easy to use that almost all the PCRs we train have adopted it in their units.',
			button: 'More reviews',
		},
		references: {
			title: 'Publications and References',
			subtitle:
				'DOSIMEX is cited in numerous scientific publications, professional magazine articles, and research papers. Discover how our tools contribute to the advancement of research and practice in radiation protection.',
			btnText: 'View',
			internshipsText:
				'Also find end-of-study internship reports citing DOSIMEX in their methodologies.',
			internshipsBtn: 'View',
			items: [
				{
					title: 'Predictive Dose Calculation for Better Protection',
					description:
						'SIH-Solutions article about the use of DOSIMEX at Institut Curie for predicting exposures in medical radiology.',
					url: 'https://www.sih-solutions.fr/le-calcul-predictif-de-dose-pour-une-meilleure-protection',
				},
				{
					title: 'Dose Assessment: A Prerequisite for Risk Management',
					description:
						'LinkedIn post about the use of DOSIMEX in the university hospitals of Nantes and Toulouse.',
					url: 'https://www.linkedin.com/posts/sih-solutions_dosimex-activity-6940552424990380032-wsY9/?utm_source=linkedin_share&utm_medium=member_desktop_web',
				},
				{
					title: 'Study of PMMA Layer Impact on Electronic Equilibrium',
					description:
						'Studies the impact of PMMA layers on electronic equilibrium for radiation protection instrument calibration and models X/gamma beams with DOSIMEX.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324004160',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Beam Quality Definition in Medical Context',
					description:
						'Uses DOSIMEX to define beam qualities (X and gamma) in medical context and analyze the influence of PMMA thickness on calibration factors.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324001532',
					authors: 'Talbi A. et al.',
					year: '2024',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Radiation Protection Work for Examination Cell - INB 164',
					description:
						'Radiation protection work for commissioning an examination cell: comparison/use of three codes including DOSIMEX alongside MicroShield and RayXpert.',
					url: 'https://inis.iaea.org/records/8q3yn-jja37',
					authors: 'CEDRA Study',
					year: '2018',
					journal: 'INIS - IAEA Database',
				},
				{
					title: 'Dosimetry Optimization Study - Software Validation',
					description:
						'Dosimetry optimization study; X-ray beam simulations performed with DOSIMEX (description of software validation argument).',
					url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4896352',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'SSRN - Preprint',
				},
				{
					title: 'DOSIMEX - Radiation Protection Codes Available to Everyone',
					description:
						'Presentation article "Dosimex - radiation protection calculation codes available to everyone" (reference source on the package and its modules). Useful to cite when justifying the use of DOSIMEX in a method.',
					url: 'https://inis.iaea.org/records/xaj40-pdm79',
					authors: 'Vivier A., Lopez G.',
					year: '2016',
					journal: 'Ionizing Radiation, Measurement and Protection Techniques - INIS',
				},
			],
		},
	},
	testimonials: {
		header: {
			title: 'User feedback',
			subtitle: 'Excerpts from user feedback collected through a survey conducted in April 2018.',
			disclaimer: 'The opinions expressed here are solely those of the authors in a personal capacity and do not represent the position of their respective institutions.',
		},
		cta: {
			title: 'Convinced?',
			button: 'Request a quote',
			trialButton: 'Try Dosismart',
		},
	},
	contact: {
		header: {
			title: 'Quote or demonstration',
			subtitle: 'Describe your needs.',
		},
		info: {
			phone: { label: 'Phone', value: '06 89 70 90 35' },
			demo: { label: 'Demo', value: 'Video conference available' },
		},
	},
	software: {
		header: {
			title: 'Radiation protection calculation tools for everyone',
			description:
				'The Dosimex pack includes 17 radiation protection calculation utilities in Excel: 6 operational codes, 6 learning modules and 5 measurement tools. Point source gamma calculation is also available in Dosismart (web browser).',
			langNote: 'Most tools are available in French and English.',
			anchors: [
				{ label: 'Operational pack', href: '#pack-ope' },
				{ label: 'Learning pack', href: '#pack-peda' },
				{ label: 'Measurement pack', href: '#pack-mes' },
			],
		},
		dosismartBanner: {
			title: 'Dosismart: gamma calculation in the browser',
			text: 'Point source gamma calculation is already available in Dosismart, our web application. 3D sources and X-ray generator coming soon. No installation, any OS.',
			button: 'Try Dosismart',
		},
		packOpe: {
			title: 'Operational pack',
			description:
				'These calculation tools enable to estimate the radiological risks at their correct levels and to design the necessary protections',
			tools: [
				{
					name: 'DOSIMEX-GX 3.2 — Gamma emitters',
					description:
						'Deterministic calculation code of dose rate for gamma emitters (volumic sources, surface source…). With many options: skyshine, bremsstrahlung, zoning, build-up',
					videoId: 'oiYwIvxnxHU',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-GX 3.2 — X-ray generators',
					description:
						'Deterministic calculation code of dose rate for X-ray generators (primary and scattered beam), with NF C15-160/2018 calculation worksheet option',
					videoId: 'xriiq6v47oE',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-B 3.2',
					description:
						'Deterministic calculation code of beta emitter dose rate and monoenergetic electrons. Taking into account volumetric sources (beaker, syringe) or surface sources (skin contamination)',
					videoId: '4Cfya_rHa04',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-N 3.2',
					description:
						'Monte-Carlo calculation code of neutron emitter dose rate (Am/Be type) with biological protection (water, polyethylene, Boron, Cadmium etc.). Pedagogical module with neutron trajectory visualization',
					videoId: '7emAJHES-fw',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-I 3.2',
					description:
						'Internal exposure calculation code. In accordance with the decree of November 16, 2023. Consideration of leakage kinetics, renewal, ground deposition. Atmospheric transfer calculations',
					videoId: 'CnqQhyB6cEo',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-MN 3.2',
					description:
						'Data management utility to know the absorbed doses per unit of activity administered for ICRP 53, 80, 106 and 128 radiopharmaceuticals',
					videoId: 'sj-FVjP87jA',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-GAMMAGRAPHY',
					description:
						'Tool dedicated to the calculation of zoning in gammagraphy for 4 sources: Se 75, Cs 137, Co 60 and Ir 192. Isodose and operational zoning calculations. Lead, concrete, steel, air shield',
					videoId: 'oJYfQDhBP68',
					frOnly: true,
				},
			],
		},
		packPeda: {
			title: 'Learning pack',
			description:
				'They provide a better understanding of the physics of radiation-matter interaction, which is the source of the generated doses, as well as of the protective capacities of the screens that can be used',
			tools: [
				{
					name: 'Photon Interaction 3.2',
					description:
						'Utility implementing the principles of photon-matter interactions in materials with various applications: kerma calculation, dose, mean free path, Compton effect, trajectory visualization (Monte-Carlo)',
					videoId: 'cBQ5-CiqqT4',
					frOnly: false,
				},
				{
					name: 'Charged Particles Interaction 3.2',
					description:
						'Utility implementing the principles of charged particle-matter interactions in materials with various applications: range calculation, fluence-dose coefficient, application to beta spectra',
					videoId: 'vXT2h8GJ8Qk',
					frOnly: false,
				},
				{
					name: 'Serious Game 3.2',
					description:
						'Pedagogical utility allowing to highlight the essential parameters of radiation protection: distance, time, screen, activity, radionuclide nature',
					videoId: 'pYbgwudKniA',
					frOnly: false,
				},
				{
					name: 'ICRU 57 Coefficients 3.2',
					description:
						'Utility allowing to know the fluence-dose equivalent coefficients and normalized air kerma for electrons, photons and neutrons',
					videoId: 'Ltk5x2dW_VI',
					frOnly: false,
				},
				{
					name: 'Nuclear meter',
					description:
						'Nuclear meter simulator that realistically reproduces statistical aspects, efficiency concept, uncertainties, and decision thresholds',
					videoId: 'fIEWzgTzC2g',
					frOnly: true,
				},
				{
					name: 'Radioactive decay',
					description:
						'Simulation tool for understanding the probabilistic aspects of nuclear decay: lifetime, period, fluctuation, decay law',
					videoId: 'v8RMSH0qryE',
					frOnly: true,
				},
			],
		},
		packMes: {
			title: 'Measurement pack',
			description: 'Utilities related to the measurement of ionizing radiation',
			tools: [
				{
					name: 'TAGE code (Total Absorption Gamma Efficiency)',
					description:
						'Deterministic code calculating the total absorption efficiency in gamma spectrometry, with dead layer correction (characterization), coincidence correction and efficiency of sum peaks',
					videoId: 'vSI75UZ_9UQ',
					frOnly: false,
				},
				{
					name: 'Co3 code',
					description:
						'Code for calculating the Conversion Coefficient of Contaminameters allowing to calculate the efficiency (Bq/cm2/cps) of various instruments and to obtain the surface activities versus the nature of the probe and the isotopic spectrum measured',
					videoId: '2Mq-TR8cG-o',
					frOnly: false,
				},
				{
					name: 'Random variables composition',
					description:
						'Utility allowing to combine up to 5 variables of different types by Monte-Carlo method. Accompanied by complete course documents on the subject of uncertainty calculations',
					frOnly: false,
				},
				{
					name: 'Decision threshold calculation',
					description:
						'Utility to determine the decision threshold and the detection limit in nuclear measurement. Accompanied by course materials',
					videoId: 'aA4QUutuaJc',
					frOnly: false,
				},
				{
					name: 'Calibration line',
					description:
						'Tool for constructing a calibration curve that takes into account uncertainties in the standards. With a set of tests: analysis of variance, non-regression test. With inverse Bayesian projection, decision threshold calculation, and detection limit',
					frOnly: true,
				},
			],
		},
		more: {
			title: 'More resources',
			links: [
				{ label: 'Dosimex-GX user manuals', href: '/manuals#manuals' },
				{ label: 'Complete validation files', href: '/manuals#validations' },
				{ label: 'Gamma source validation extracts', href: '/Folders/extrait_validation_gamma.pdf', pdf: true },
				{ label: 'X-ray generator validation', href: '/Folders/extrait_validation_géné_X.pdf', pdf: true },
				{ label: "What's new in Dosimex-GX 3.2", href: '/Folders/Modification_Dosimex GX_3.0.pdf', pdf: true },
				{ label: 'Our reading selection', href: '/books' },
			],
		},
		ask: {
			title: 'Any questions?',
			text: 'For a quote or to try Dosismart, contact us here or by phone at 06 89 70 90 35',
			labelButton: 'Contact us',
		},
		watchVideo: 'Watch video on YouTube',
		videosButton: 'Check out all videos',
	},
	product: {
		title: 'Product data sheet',
		schemaDescription: 'Annual single-user license',
		buttonKnowMore: 'Read more',
		description:
			'DOSIMEX 3.2 — 17 professional codes in Excel: 6 operational codes (dose calculations, zoning, shielding), 6 interactive educational modules, 5 measurement and analysis utilities. Dosismart access included (web application, currently point source gamma calculation). Technical support included.',
		partE: {
			title: 'Pack content',
			items: [
				'All the codes and utilities (17) of the operational (6), learning (6) and measurement (5) packs presented on this site',
				'The associated documentation: user manual and validation file for each code.',
				'Course documents (11): nuclear physics, nuclear measurement, charged particle MRI, photon MRI, neutron MRI, operational quantities, decision threshold: principles and application, statistics: principles, uncertainties, and hypothesis testing.',
				'Appendices (19) of the book "Calculation of doses generated by ionizing radiation" (EDP Sciences 2016).',
			],
			softwareLink: 'Learn more about the tools',
			manualsLink: 'View documentation',
		},
		between:
			'A general summary (SOMMAIRE_GENERAL.pps) at the root of the folders allows navigation through the entire Dosimex package.',
		prerequisites: {
			title: 'Prerequisites',
			text: 'Dosimex: VBA/Excel, Windows XP to 11, Excel 2003 to 2024. Virtual machine required on Mac/Linux. Dosismart: web browser (Chrome, Firefox, Edge, Safari), any OS, no installation.',
		},
		trialBanner: {
			title: 'Try Dosismart for free',
			text: 'Dosismart is the web application for radiation protection calculations. Point source gamma available now — 3D sources and X-ray coming soon. No installation, no credit card.',
			button: 'Start trial',
		},
		pricing: {
			title: 'Pricing',
			packageTitle: 'DOSIMEX 3.2 Pack — Single-user License (Dosismart access included)',
			annual: {
				title: 'Annual License',
				price: '\u20AC500 excl. VAT',
				duration: 'per year',
				features: [
					'Updates included for 1 year',
					'Technical support included',
					'Instant installation after purchase',
					'Annual renewal required',
				],
			},
			triennial: {
				title: '3-Year License',
				price: '\u20AC1,000 excl. VAT',
				duration: 'for 3 years',
				features: [
					'Updates included for 3 years',
					'Technical support included',
					'Instant installation after purchase',
					'3-year validity without renewal',
				],
				savings: 'Save \u20AC500 over 3 years!',
			},
			orderTitle: 'How to order?',
			orderText:
				'Request your personalized quote using the form below. We will respond promptly with your quote and payment terms.',
			quoteButton: 'Request a quote',
		},
		faq: {
			title: 'Frequently Asked Questions',
			questions: [
				{
					question: 'What is the difference between Dosimex and Dosismart?',
					answer:
						"Dosimex is the complete Excel pack with all 17 calculation tools. Dosismart is the web application, accessible in the browser without installation. Dosismart currently offers point source gamma calculation, with 3D sources and X-ray generator under development. Dosismart access is included with the Dosimex license.",
				},
				{
					question: 'What are the prerequisites?',
					answer:
						'Dosimex: Excel 2003 to 2024, Windows. Dosismart: modern web browser (Chrome, Firefox, Edge, Safari), any OS, no installation.',
				},
				{
					question: 'Are updates included?',
					answer:
						'Yes. Dosimex and Dosismart updates included with the license, plus technical support.',
				},
				{
					question: 'How does the free Dosismart trial work?',
					answer:
						'The Dosismart trial is free, with no commitment and no credit card. You get access to point source gamma calculation directly in your browser. No installation required.',
				},
			],
		},
		contact: {
			title: 'Quote, free Dosismart trial, questions?',
			text: 'Feel free to contact us via the form below or by phone at ',
			phone: '06 89 70 90 35',
		},
	},
	about: {
		header: { title: 'Our team' },
		gerald: {
			paragraphs: [
				'I began my career in 1997 in the French Navy. After training in radiation protection, I joined the RPD at Ile Longue on nuclear submarines, then the EAMEA where I taught radioactivity, dosimetry and nuclear measurement. That is when I started building my own calculation tools for coursework.',
				'In 2010, at the Cherbourg Arsenal RPD, I created the Dosimex-I code (atmospheric transfer). Since 2013, at the Orano La Hague radiation protection department, I have faced most of the site radiation protection challenges: dismantling, high activity, vitrification, waste treatment.',
				'In all these situations, the Dosimex tools proved invaluable for analyzing radiological risk. Field experience has continuously fed back into improving the codes.',
			],
		},
		alain: {
			paragraphs: [
				"After the Ecole de l'Air (class of '80), I was designated PCR for X-rays on Mirage IV canopies. With no radiation meter or calculation tools, I had no idea of the radiological risk involved. In 1990, at the Ecole Atomique de Cherbourg, I began teaching nuclear physics and understanding radiation-matter interaction.",
				"My first modeling work — stopping power of charged particles using Bethe's formula — was a revelation: the agreement between theoretical prediction and measurements with conversion electrons was striking. At CEA then INSTN Saclay, I created the training course on dosimetry of ionizing radiation.",
				'Meeting Gerald Lopez, I recognized his modeling skills and extraordinary work capacity. In 2010, when EDP agreed to publish our book on dose calculations, it was clear it needed to be accompanied by calculation utilities. This is how Dosimex was born.',
			],
		},
		epilogue: 'Epilogue: it is thanks to Dosimex that I was finally able, 25 years later, to assess the radiological risk from X-ray generators — a risk that is far from negligible.',
		cta: {
			title: 'Discover our tools',
			button: 'See the product',
		},
	},
	books: {
		header: { title: 'Readings' },
		viewBook: 'View book',
		coverAlt: 'Cover:',
		byAuthor: 'by',
		items: [
			{ extract: 'This book is intended for students studying for careers in the nuclear industry, nuclear medicine or research. Users of ionizing radiation will also find useful and up-to-date information.', author: 'Arnaud Boquet', title: 'Radiation Protection of Workers, Patients and the Public' },
			{ extract: 'This book has two complementary objectives: to provide the reader an understanding of the physical principles at work when a target is exposed to ionizing radiation, and to propose simple calculation tools to evaluate the absorbed doses.', author: 'Alain Vivier and Gérald Lopez', title: 'Calculation of Doses Generated by Ionizing Radiation' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of unsealed sources and sealed sources necessary for their control.', author: 'Hugues Bruchet', title: 'RPC — Radiation Protection Principles and Regulations' },
			{ extract: 'The role of the competent person in radiation protection (PCR) has developed widely in recent years. This volume is intended for PCRs or future PCRs involved in medical sector facilities.', author: 'Hugues Bruchet, Amélie Roué et Christine Jimonet', title: 'RPC — Medical Sector' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of X-ray generators and sealed sources.', author: 'Jean-Claude Moreau and Marc Ammerich', title: 'RPC — Industry and Research Sector' },
			{ extract: 'It was time to retrace the history of nuclear physics. Bernard Fernandez takes you by the hand to guide you through the meanders of a complicated but fascinating science.', author: 'Bernard Fernandez', title: 'From Atom to Nucleus — A Historical Approach to Nuclear Physics' },
			{ extract: "Intended for a wide audience, Le monde subatomique describes the evolution of ideas about the interactions and constituents of matter, from the discovery of the neutron to that of the Z° boson.", author: 'Luc Valentin', title: 'The Subatomic World' },
			{ extract: 'This book aims to synthesize many years of experience in the field of external dosimetry and protection techniques against this type of exposure in the industrial, research and medical fields.', author: 'Rodolphe Antoni et Laurent Bourgois', title: 'Shielding Techniques and Radiation Protection' },
			{ extract: 'This book reviews the state of the art in dosimetric calculations, ionizing radiation metrology and radiation protection through problems related to concrete applications in the field.', author: 'Laurent Bourgois and Rodolphe Antoni', title: 'Dosimetry of Ionizing Radiation and Radiation Protection' },
			{ extract: 'Radioactivity is everywhere, it surrounds us. This book, without complex mathematical formulas, will allow all readers to better understand the role and the work of radiation protectionists.', author: 'Marc Ammerich', title: 'Radioactivity Under Surveillance' },
			{ extract: 'These books are adapted to students in master radiation protection, engineering school but also to students specialized in BTS or license radiation protection.', author: 'Marc Ammerich', title: 'Radiation Protection Exercises — Volume 1' },
		],
	},
	manuals: {
		header: {
			title: 'Documentation',
			description: 'To help you evaluate the possibilities offered by Dosimex-GX, you can download all the documentation associated with this code:',
			anchors: ['User manuals', 'The validation files', 'Some end of study internships reports using Dosimex'],
		},
		manuals: {
			title: 'User manuals',
			items: ['Gamma dose manual', 'Generator X-ray manual', 'Manual + Validation NF C15-160', 'Practical values in radiology'],
		},
		validations: {
			title: 'Validation files and MCNP references',
			items: ['Gamma emission validation file', 'X-ray generator validation file', 'X-ray generator reference MCNP/CEA', 'MCNP/AREVA radionuclide reference', 'X attenuation reference'],
		},
		internships: {
			title: 'End of study internships reports vs Dosimex',
			items: ['Ulysse research papers', 'Microshield vs Dosimex 1 research papers', 'Microshield vs Dosimex 2 research papers', 'Microshield vs Dosimex 3 research papers'],
		},
	},
	training: {
		videoTitle: 'Dosimex \u2014 Presentation',
		header: {
			title: 'Training',
			description: 'We offer on-site or videoconference intra-company training courses from 1 to 3 days to learn how to use Dosimex tools. These trainings are based on tutorials integrating the use of Dosimex tools in the broader framework of radiological risk analysis applied to concrete cases encountered in the industrial and medical world.',
		},
		section1: {
			title: 'Examples of topics covered, which can be modified according to the needs:',
			items: [
				'Calculation of protection around medical and industrial X-ray generators',
				'Application NF C 15-160',
				'Management of a high activity Radium source',
				'Technetium 99m syringe and operator protection',
				'Fluorine 18 contamination',
				'Co60, Ir192, Sr95, Cs137 gamma radiography',
				"EDF's preferred radionuclides",
				'ALARA approach on primary piping',
				'Diffusion in a blockhouse baffle',
				'Radiation protection around a fuel storage pool',
				'Biological protection of a Californium 252 source (neutrons + gamma)',
				'Food ionizations',
				'High activity Strontium-Yttrium 90 source',
				'Radiation protection analysis of a fission product waste package (CSDV)',
			],
		},
		section2: {
			title: 'In partnership with Veolia Nuclear Solutions, we offer other training courses on the following topics:',
			items: ['Nuclear physics and radioactivity', 'Interaction between radiation and matter', 'Decision threshold (ISO 11929)', 'Gamma spectrometry'],
			button: 'Training catalogue',
		},
		questions: {
			title: 'Any questions?',
			text: 'Feel free to contact us via the form below or by phone at 06 89 70 90 35',
			button: 'Contact us',
		},
	},
	videos: {
		header: {
			title: 'Videos',
			description: 'You will find below all the videos concerning the operational, learning and measurement packages. We also propose on our YouTube channel other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Watch our YouTube channel',
		},
		packTitle: 'Videos from the pack ',
		packOpe: { name: 'operational', label: 'operational pack' },
		packPeda: { name: 'learning', label: 'learning pack' },
		packMes: { name: 'measurement', label: 'measurement pack' },
	},
	contactForm: {
		title: 'Contact us',
		labels: {
			name: 'Name',
			email: 'Email',
			phone: 'Phone',
			company: 'Company',
			address: 'Address',
			subject: 'Subject',
			message: 'Message',
		},
		errors: {
			name: 'Please enter a name',
			email: 'Please enter a valid email',
			phone: 'Please enter a valid phone number',
			message: 'Please enter a message',
		},
		button: 'Send',
		sending: 'Sending...',
		messageSent: 'Message sent!',
		messageNotSent: 'Message not sent',
	},
	footer: {
		col1: {
			p: [
				'Copyright © 2026 Designed by Dosimex',
				'All rights reserved',
				'06 89 70 90 35',
				'Follow us on social media',
			],
		},
		col2: {
			title: 'Resources',
			p: ['Dosismart', 'Video archives', 'Manuals and validations', 'Readings'],
		},
		col3: {
			title: 'Company',
			p: ['About us', 'Legal', 'Contact'],
		},
		manageCookies: 'Manage cookies',
	},
} as const
