export const en = {
	seo: {
		home: {
			title: 'Dosimex — Professional Radiation Protection Software',
			description: 'Dosimex: 17 professional tools for radiation protection. Gamma, beta, neutron dose calculations, internal exposure and atmospheric transfer.',
		},
		software: {
			title: 'Calculation Tools — Dosimex',
			description: 'Explore 17 Dosimex tools: operational codes (gamma, beta, neutron), interactive learning modules and measurement utilities for radiation protection.',
		},
		product: {
			title: 'Product & Pricing — Dosimex',
			description: 'Dosimex 3.2 + Dosismart pack: 17 calculation codes, single-user license from €500/year excl. VAT. 14-day free Dosismart trial, no commitment.',
		},
		training: {
			title: 'Radiation Protection Training — Dosimex',
			description: 'Dosimex in-house training from 1 to 3 days: hands-on calculation tools, practical exercises applied to real radiation protection cases.',
		},
		books: {
			title: 'Recommended Readings — Dosimex',
			description: 'Curated selection of reference books on radiation protection, dosimetry and nuclear physics recommended by Dosimex experts.',
		},
		manuals: {
			title: 'Documentation & Validation — Dosimex',
			description: 'User manuals, MCNP validation files and internship reports for Dosimex-GX. Complete documentation available as downloadable PDFs.',
		},
		videos: {
			title: 'Videos & Tutorials — Dosimex',
			description: 'Explanatory videos for each Dosimex tool: operational, learning and measurement packs. Visit our YouTube channel for more.',
		},
		about: {
			title: 'Our Team — Dosimex',
			description: 'Meet Gérald Lopez and Alain Vivier, the creators of Dosimex. Over 30 years of experience in radiation protection and dosimetry.',
		},
		contact: {
			title: 'Contact & Quote — Dosimex',
			description: 'Contact Dosimex for a quote, demo or free trial. Response within 24 hours. Video conference demonstration available.',
		},
	},
	altText: {
		logo: 'DOSIMEX - Radiation Dosimetry Software',
		flagUk: 'UK flag - DOSIMEX available in English',
		decorativePattern: 'Decorative geometric pattern background',
		radiationSymbol: 'DOSIMEX radiation safety symbol - clover leaf icon',
		carouselMain: 'DOSIMEX radiation dosimetry software interface mockup',
		carouselScreens: 'Banner image',
		trainingMaterials: 'DOSIMEX radiation safety training course materials',
		manualCover: 'Manual cover',
		cardIcon: 'Icon',
	},
	navbar: {
		items: ['Product', 'Training', 'Documentation', 'About us', 'Contact'],
		button: 'Free Trial',
		quoteButton: 'Request a quote',
	},
	home: {
		hero: {
			title: 'Radiation protection calculation tools for everyone',
			subtitle:
				'A set of practical, easy-to-use, validated calculation tools that address many situations encountered in radiation protection. They will allow you to improve your expertise level.',
			promo:
				'New: Dosismart -- Dosimex calculation codes, now in the browser. No installation required.',
			cta: 'Discover',
			trialButton: 'Free Trial',
			referencesButton: 'Publications',
		},
		partners: {
			title: 'Partners',
			descriptions: [
				'A company that loves projects. So do we',
				'The first to use Dosimex in PCR training',
				'Partner for radiation protection training and Dosimex user',
				'The only ones in France who know how to encrypt Excel (and other Microsoft products). Without them we simply would not exist',
				'We are proud to help them in their missions',
				'Our historical editor for the book "calculation of doses generated by ionizing radiation"',
				'Use Dosimex a lot in their calculations',
				'Among the first to support us. And they continue to do so. Thank you',
				'Our long-time partner for training in gamma spectrometry and other fields',
				'They have honored us with their appreciation of our codes. And we highly recommend the RayXpert code',
			],
		},
		offers: {
			title: 'What we offer',
			description:
				'A set of calculation tools (total of 17) covering most of the field in radiation protection: gamma, beta and neutron external exposure, internal exposure, atmospheric transfer and more. You will find on this site explanatory videos for each tool and their validation files (downloadable pdf).',
			card1: {
				title: 'Dosimex + Dosismart',
				description:
					'17 Dosimex calculation tools (Excel) and Dosismart, their web version running in the browser',
			},
			card2: {
				title: 'Documentation',
				description:
					'Validated via MCNP, RayXpert, Microshield and Mercurad. Access all documentation associated with Dosimex-GX',
			},
			card3: {
				title: 'Training',
				description:
					'We guide you to take in hand these calculation tools by adapting us to your specific problems',
			},
		},
		callToAction: {
			title: 'Dosimex + Dosismart: Excel and web, same calculation codes',
			button: 'Request a quote',
			trialButton: '14-day free trial',
		},
		numbers: {
			items: [
				{ value: '+30 years', label: 'of experience' },
				{ value: '+1000', label: 'convinced radioprotectionists' },
				{ value: '35', label: 'days of support provided' },
			],
		},
		videoTitle: 'Dosimex Presentation',
		videos: {
			title: 'Join us on YouTube',
			description:
				'We offer you other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Check out the other videos',
		},
		opinion: {
			name: 'Jean-Lionel Trolet',
			job: 'EAMEA',
			text: 'I use DOSIMEX, which gives me total satisfaction, both by the quality of its results and its ease of use, in the training of personnel from the Ministry of the Armed Forces. It has, among other things, the strength of taking into account common situations faced by MinArm agents, both in the roles of medical PCRs (thanks to the X-ray calculation module!) as well as those involved at all levels in the industrial field (from PNR to engineer). Finally, it is so easy to use that almost all the PCRs we train have adopted it in their units.',
			button: 'More reviews',
		},
		references: {
			title: 'Publications and References',
			subtitle:
				'DOSIMEX is cited in numerous scientific publications, professional magazine articles, and research papers. Discover how our tools contribute to the advancement of research and practice in radiation protection.',
			btnText: 'View',
			internshipsText:
				'Also find end-of-study internship reports citing DOSIMEX in their methodologies.',
			internshipsBtn: 'View',
			items: [
				{
					title: 'Predictive Dose Calculation for Better Protection',
					description:
						'SIH-Solutions article about the use of DOSIMEX at Institut Curie for predicting exposures in medical radiology.',
					url: 'https://www.sih-solutions.fr/le-calcul-predictif-de-dose-pour-une-meilleure-protection',
				},
				{
					title: 'Dose Assessment: A Prerequisite for Risk Management',
					description:
						'LinkedIn post about the use of DOSIMEX in the university hospitals of Nantes and Toulouse.',
					url: 'https://www.linkedin.com/posts/sih-solutions_dosimex-activity-6940552424990380032-wsY9/?utm_source=linkedin_share&utm_medium=member_desktop_web',
				},
				{
					title: 'Study of PMMA Layer Impact on Electronic Equilibrium',
					description:
						'Studies the impact of PMMA layers on electronic equilibrium for radiation protection instrument calibration and models X/gamma beams with DOSIMEX.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324004160',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Beam Quality Definition in Medical Context',
					description:
						'Uses DOSIMEX to define beam qualities (X and gamma) in medical context and analyze the influence of PMMA thickness on calibration factors.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324001532',
					authors: 'Talbi A. et al.',
					year: '2024',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Radiation Protection Work for Examination Cell - INB 164',
					description:
						'Radiation protection work for commissioning an examination cell: comparison/use of three codes including DOSIMEX alongside MicroShield and RayXpert.',
					url: 'https://inis.iaea.org/records/8q3yn-jja37',
					authors: 'CEDRA Study',
					year: '2018',
					journal: 'INIS - IAEA Database',
				},
				{
					title: 'Dosimetry Optimization Study - Software Validation',
					description:
						'Dosimetry optimization study; X-ray beam simulations performed with DOSIMEX (description of software validation argument).',
					url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4896352',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'SSRN - Preprint',
				},
				{
					title: 'DOSIMEX - Radiation Protection Codes Available to Everyone',
					description:
						'Presentation article "Dosimex - radiation protection calculation codes available to everyone" (reference source on the package and its modules). Useful to cite when justifying the use of DOSIMEX in a method.',
					url: 'https://inis.iaea.org/records/xaj40-pdm79',
					authors: 'Vivier A., Lopez G.',
					year: '2016',
					journal: 'Ionizing Radiation, Measurement and Protection Techniques - INIS',
				},
			],
		},
	},
	contact: {
		header: {
			title: 'Quote or demonstration',
			subtitle:
				'Describe your needs below. Response within 24 hours. Video conference demonstration available.',
		},
	},
	software: {
		header: {
			title: 'Product',
			description:
				'The DOSIMEX pack is your reference digital solution for all radiation protection calculations. It includes 17 utilities: precise and reliable codes for operational calculations, clear, rich, and interactive educational modules, and tools covering measurement aspects. Designed to be fast, reliable, and easy to use, DOSIMEX becomes an indispensable tool for saving time, working safely, and achieving accurate results.',
			anchors: [
				{ label: 'Operational pack', href: '#pack-ope' },
				{ label: 'Learning pack', href: '#pack-peda' },
				{ label: 'Measurement pack', href: '#pack-mes' },
			],
		},
		dosismartBanner: {
			title: 'New: these tools also exist as a web version',
			text: 'Dosismart runs the Dosimex calculation codes in the browser. No installation, works on any OS.',
			button: 'Try Dosismart',
		},
		packOpe: {
			title: 'Operational pack',
			description:
				'These calculation tools enable to estimate the radiological risks at their correct levels and to design the necessary protections',
			tools: [
				{
					name: 'DOSIMEX-GX 3.2',
					description:
						'Deterministic calculation code of dose rate for gamma emitters and X-ray generators, with NF C15-160/2018 calculation worksheet option. With many options: skyshine, bremsstrahlung, zoning, build-up',
					videoId: 'E5eWKTJaNxQ',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-B 3.2',
					description:
						'Deterministic calculation code of beta emitter dose rate and monoenergetic electrons. Taking into account volumetric sources (beaker, syringe) or surface sources (skin contamination)',
					videoId: '4Cfya_rHa04',
					frOnly: true,
				},
				{
					name: 'DOSIMEX-N 3.2',
					description:
						'Monte-Carlo calculation code of neutron emitter dose rate (Am/Be type) with biological protection (water, polyethylene, Boron, Cadmium etc.). Pedagogical module with neutron trajectory visualization',
					videoId: '7emAJHES-fw',
					frOnly: true,
				},
				{
					name: 'DOSIMEX-I 3.2',
					description:
						'Internal exposure calculation code. In accordance with the decree of November 16, 2023. Consideration of leakage kinetics, renewal, ground deposition. Atmospheric transfer calculations',
					videoId: 'CnqQhyB6cEo',
					frOnly: true,
				},
				{
					name: 'DOSIMEX-MN 3.2',
					description:
						'Data management utility to know the absorbed doses per unit of activity administered for ICRP 53, 80, 106 and 128 radiopharmaceuticals',
					videoId: 'sj-FVjP87jA',
					frOnly: true,
				},
				{
					name: 'DOSIMEX-GAMMAGRAPHY',
					description:
						'Tool dedicated to the calculation of zoning in gammagraphy for 4 sources: Se 75, Cs 137, Co 60 and Ir 192. Isodose and operational zoning calculations. Lead, concrete, steel, air shield',
					videoId: 'oJYfQDhBP68',
					frOnly: true,
				},
			],
		},
		packPeda: {
			title: 'Learning pack',
			description:
				'They provide a better understanding of the physics of radiation-matter interaction, which is the source of the generated doses, as well as of the protective capacities of the screens that can be used',
			tools: [
				{
					name: 'Photon Interaction 3.2',
					description:
						'Utility implementing the principles of photon-matter interactions in materials with various applications: kerma calculation, dose, mean free path, Compton effect, trajectory visualization (Monte-Carlo)',
					videoId: 'cBQ5-CiqqT4',
					frOnly: true,
				},
				{
					name: 'Charged Particles Interaction 3.2',
					description:
						'Utility implementing the principles of charged particle-matter interactions in materials with various applications: range calculation, fluence-dose coefficient, application to beta spectra',
					videoId: 'vXT2h8GJ8Qk',
					frOnly: true,
				},
				{
					name: 'Serious Game 3.2',
					description:
						'Pedagogical utility allowing to highlight the essential parameters of radiation protection: distance, time, screen, activity, radionuclide nature',
					videoId: 'pYbgwudKniA',
					frOnly: true,
				},
				{
					name: 'ICRU 57 Coefficients 3.2',
					description:
						'Utility allowing to know the fluence-dose equivalent coefficients and normalized air kerma for electrons, photons and neutrons',
					videoId: 'Ltk5x2dW_VI',
					frOnly: true,
				},
				{
					name: 'Nuclear meter',
					description:
						'Nuclear meter simulator that realistically reproduces statistical aspects, efficiency concept, uncertainties, and decision thresholds',
					videoId: 'oJYfQDhBP68',
					frOnly: true,
				},
				{
					name: 'Radioactive decay',
					description:
						'Simulation tool for understanding the probabilistic aspects of nuclear decay: lifetime, period, fluctuation, decay law',
					videoId: 'v8RMSH0qryE',
					frOnly: true,
				},
			],
		},
		packMes: {
			title: 'Measurement pack',
			description: 'Utilities related to the measurement of ionizing radiation',
			tools: [
				{
					name: 'TAGE code (Total Absorption Gamma Efficiency)',
					description:
						'Deterministic code calculating the total absorption efficiency in gamma spectrometry, with dead layer correction (characterization), coincidence correction and efficiency of sum peaks',
					videoId: 'vSI75UZ_9UQ',
					frOnly: true,
				},
				{
					name: 'Co3 code',
					description:
						'Code for calculating the Conversion Coefficient of Contaminameters allowing to calculate the efficiency (Bq/cm2/cps) of various instruments and to obtain the surface activities versus the nature of the probe and the isotopic spectrum measured',
					videoId: '2Mq-TR8cG-o',
					frOnly: true,
				},
				{
					name: 'Random variables composition',
					description:
						'Utility allowing to combine up to 5 variables of different types by Monte-Carlo method. Accompanied by complete course documents on the subject of uncertainty calculations',
					frOnly: true,
				},
				{
					name: 'Decision threshold calculation',
					description:
						'Utility to determine the decision threshold and the detection limit in nuclear measurement. Accompanied by course materials',
					videoId: 'aA4QUutuaJc',
					frOnly: true,
				},
				{
					name: 'Calibration line',
					description:
						'Tool for constructing a calibration curve that takes into account uncertainties in the standards. With a set of tests: analysis of variance, non-regression test. With inverse Bayesian projection, decision threshold calculation, and detection limit',
					frOnly: true,
				},
			],
		},
		more: {
			title: 'More resources',
			links: [
				{ label: 'Dosimex-GX user manuals', href: '/manuals' },
				{ label: 'Complete validation files', href: '/manuals' },
				{ label: 'Gamma source validation extracts', href: '/manuals' },
				{ label: 'X-ray generator validation', href: '/manuals' },
				{ label: "What's new in Dosimex-GX 3.2", href: '/manuals' },
				{ label: 'Our reading selection', href: '/books' },
			],
		},
		ask: {
			title: 'Any questions?',
			text: 'For a quote or to try Dosismart, contact us here or by phone at 06 89 70 90 35',
			labelButton: 'Contact us',
		},
		watchVideo: 'Watch video on YouTube',
		videosButton: 'Check out all videos',
	},
	product: {
		title: 'Product data sheet',
		schemaDescription: 'Annual single-user license',
		buttonKnowMore: 'Read more',
		description:
			'DOSIMEX 3.2 + DOSISMART — 17 Dosimex professional codes (VBA/Excel) and Dosismart, their web version. 6 operational codes (dose calculations, zoning, shielding), 6 interactive educational modules, 5 measurement and analysis utilities. Dosimex license + Dosismart access included. Technical support included.',
		partE: {
			title: 'Pack content',
			items: [
				'All the codes and utilities (17) of the operational (6), learning (6) and measurement (5) packs presented on this site',
				'The associated documentation: user manual and validation file for each code.',
				'Course documents (11): nuclear physics, nuclear measurement, charged particle MRI, photon MRI, neutron MRI, operational quantities, decision threshold: principles and application, statistics: principles, uncertainties, and hypothesis testing.',
				'Appendices (19) of the book "Calculation of doses generated by ionizing radiation" (EDP Sciences 2016).',
			],
			softwareLink: 'Learn more about the tools',
			manualsLink: 'View documentation',
		},
		between:
			'A general summary (SOMMAIRE_GENERAL.pps) at the root of the folders allows navigation through the entire Dosimex package.',
		prerequisites: {
			title: 'Prerequisites',
			text: 'Dosimex: VBA/Excel, Windows XP to 11, Excel 2003 to 2024. Virtual machine required on Mac/Linux. Dosismart: web browser (Chrome, Firefox, Edge, Safari), any OS, no installation.',
		},
		trialBanner: {
			title: 'Free trial — Dosismart, 14 days',
			text: 'Dosismart is the web version of Dosimex calculation codes. Runs in the browser, no installation. No commitment, no credit card.',
			button: 'Start trial',
		},
		pricing: {
			title: 'Pricing',
			packageTitle: 'DOSIMEX 3.2 + DOSISMART Pack — Single-user License',
			annual: {
				title: 'Annual License',
				price: '\u20AC500 excl. VAT',
				duration: 'per year',
				features: [
					'Updates included for 1 year',
					'Technical support included',
					'Instant installation after purchase',
					'Annual renewal required',
				],
			},
			triennial: {
				title: '3-Year License',
				price: '\u20AC1,000 excl. VAT',
				duration: 'for 3 years',
				features: [
					'Updates included for 3 years',
					'Technical support included',
					'Instant installation after purchase',
					'3-year validity without renewal',
				],
				savings: 'Save \u20AC500 over 3 years!',
			},
			orderTitle: 'How to order?',
			orderText:
				'Request your personalized quote using the form below. We will respond promptly with your quote and payment terms.',
			quoteButton: 'Request a quote',
		},
		faq: {
			title: 'Frequently Asked Questions',
			questions: [
				{
					question: 'Why two versions?',
					answer:
						'Dosimex runs in Excel, integrated into your existing workflows. Dosismart runs in the browser, usable on any device without installation. Both use the same calculation codes.',
				},
				{
					question: 'What are the prerequisites?',
					answer:
						'Dosimex: Excel 2003 to 2024, Windows. Dosismart: modern web browser (Chrome, Firefox, Edge, Safari), any OS, no installation.',
				},
				{
					question: 'Are updates included?',
					answer:
						'Yes. Dosimex and Dosismart updates included with the license, plus technical support.',
				},
				{
					question: 'How does the free trial work?',
					answer:
						'Dosismart trial: 14 days, no commitment, no credit card. Full access to all calculation tools.',
				},
			],
		},
		contact: {
			title: 'Quote, free trial, questions?',
			text: 'Feel free to contact us via the form below or by phone at ',
			phone: '06 89 70 90 35',
		},
	},
	about: {
		header: { title: 'Our team' },
		gerald: {
			paragraphs: [
				'I began my career in 1997 in the French Navy as an electrical technician on weapons systems. After training as a radiation protection technician (RT), I joined the RPD at Ile Longue, with various missions focused on nuclear-armed ballistic missile submarines (SNLE): radiological assistance, reactor compartment mapping, radiological analyses in the medium activity laboratory, nuclear safety exercises...',
				"In 2003, after training as a senior technician in radiation protection (TRS) at the INSTN, I joined the Ecole des Applications Militaire à l'Energie Atomique (EAMEA) where I taught radioactivity, radiation protection, dosimetry, and nuclear measurement. From that time on, to compensate for the obvious lack of tools, I started to create my own calculation tools.",
				'In 2010, I joined the RDP of the Cherbourg Arsenal in charge of the 2SNM (Marine Nuclear Monitoring System), a system linked to the National Measurement Network (NMN). This experience allowed me, among other things, to create the Dosimex-I code, particularly on the atmospheric transfer option.',
				"Since 2013, after having published in collaboration with Alain Vivier, the book 'Calculation of dose generated by ionizing radiation', I joined the radiation protection department of the Orano site at La Hague where I was confronted with most of the site's radiation protection problems:",
				'In most of the radiation protection problems I had to face, the Dosimex tools were very useful to analyze the radiological risk. Conversely, feedback has allowed me to enrich these codes.',
			],
			timeline: [
				'2013 - 2015: monitoring of the dismantling of the UP2-400 production unit in the High Activity sector.',
				'2015 - 2017: dismantling advisor on the ELAN2B and STE2 (Effluent Treatment Station) perimeters, analysis of approaches.',
				'2017 - 2018: responsible for the radiation protection level of the High Activity perimeter of the UP2-400 plant.',
				'2018 - 2019: activity manager for the Conditioning Operational Unit: vitrification (R7/T7), waste treatment (AD2 and AD1/BDH) and hull compaction (ACC) workshops at the UP2-800 and UP3 plants at the La Hague site.',
				"In 2019, I took over responsibility for the expertise division in charge of technical support and innovation for all the sector's activities in the fields of radiation protection and conventional safety.",
			],
		},
		alain: {
			paragraphs: [
				"After studying at the Ecole de l'Air (class of '80) and being assigned to a Mirage IV maintenance unit, I was designated to be a PCR for X-rays on canopies. Apart from the X-ray generator, I had neither a radiation meter nor any calculation tools at the time, so I had no idea of the radiological risk involved.",
				'In 1990, I joined the Ecole Atomique de Cherbourg to do an atomic engineering degree. I was lucky enough to be able to stay there as a teacher.',
				"Responsible for teaching nuclear physics and a measurement laboratory, I began to understand the phenomena of radiation-matter interaction and realized that it should be possible to calculate, not just measure, a dose rate from a 1 GBq source of Cesium 137 placed at 1 m.",
				"My first modeling experience involved the calculation of the stopping power of charged particles, using Bethe's formula. I was then struck by the agreement between the theoretical prediction and the results of measurements with conversion electrons and thin copper targets. This cross validation between modeling and measurement was a revelation.",
				"In 1998, I joined the CEA, first at the RDP in Cadarache at the AtPu (plutonium workshop), then in 2000, at the INSTN in Saclay. The first training course I created there was entitled 'dosimetry of ionizing radiation'.",
				'During visits to the Ecole Atomique, I met Gérald Lopez. I quickly recognized his skills in modeling, his capacity for analysis associated with an extraordinary work capacity. At that time, he had already laid the foundations for what would become Dosimex-GX.',
				'In 2010, when EDP agreed to publish a book on dose calculations, it became clear to me that such a book should be accompanied by calculation utilities, and especially that Gérald Lopez was essential to the realization of this project. This is how Dosimex was born.',
			],
		},
		epilogue: 'Epilogue: it is thanks to Dosimex that I was finally able, 25 years later, to have an idea of the radiological risk incurred with X-ray generators, a risk that is far from negligible',
	},
	books: {
		header: { title: 'Readings' },
		viewBook: 'View book',
		coverAlt: 'Cover:',
		byAuthor: 'by',
		items: [
			{ extract: 'This book is intended for students studying for careers in the nuclear industry, nuclear medicine or research. Users of ionizing radiation will also find useful and up-to-date information.', author: 'Arnaud Boquet', title: 'Radiation Protection of Workers, Patients and the Public' },
			{ extract: 'This book has two complementary objectives: to provide the reader an understanding of the physical principles at work when a target is exposed to ionizing radiation, and to propose simple calculation tools to evaluate the absorbed doses.', author: 'Alain Vivier and Gérald Lopez', title: 'Calculation of Doses Generated by Ionizing Radiation' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of unsealed sources and sealed sources necessary for their control.', author: 'Hugues Bruchet', title: 'RPC — Radiation Protection Principles and Regulations' },
			{ extract: 'The role of the competent person in radiation protection (PCR) has developed widely in recent years. This volume is intended for PCRs or future PCRs involved in medical sector facilities.', author: 'Hugues Bruchet, Amélie Roué et Christine Jimonet', title: 'RPC — Medical Sector' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of X-ray generators and sealed sources.', author: 'Jean-Claude Moreau and Marc Ammerich', title: 'RPC — Industry and Research Sector' },
			{ extract: 'It was time to retrace the history of nuclear physics. Bernard Fernandez takes you by the hand to guide you through the meanders of a complicated but fascinating science.', author: 'Bernard Fernandez', title: 'From Atom to Nucleus — A Historical Approach to Nuclear Physics' },
			{ extract: "Intended for a wide audience, Le monde subatomique describes the evolution of ideas about the interactions and constituents of matter, from the discovery of the neutron to that of the Z° boson.", author: 'Luc Valentin', title: 'The Subatomic World' },
			{ extract: 'This book aims to synthesize many years of experience in the field of external dosimetry and protection techniques against this type of exposure in the industrial, research and medical fields.', author: 'Rodolphe Antoni et Laurent Bourgois', title: 'Shielding Techniques and Radiation Protection' },
			{ extract: 'This book reviews the state of the art in dosimetric calculations, ionizing radiation metrology and radiation protection through problems related to concrete applications in the field.', author: 'Laurent Bourgois and Rodolphe Antoni', title: 'Dosimetry of Ionizing Radiation and Radiation Protection' },
			{ extract: 'Radioactivity is everywhere, it surrounds us. This book, without complex mathematical formulas, will allow all readers to better understand the role and the work of radiation protectionists.', author: 'Marc Ammerich', title: 'Radioactivity Under Surveillance' },
			{ extract: 'These books are adapted to students in master radiation protection, engineering school but also to students specialized in BTS or license radiation protection.', author: 'Marc Ammerich', title: 'Radiation Protection Exercises — Volume 1' },
		],
	},
	manuals: {
		header: {
			title: 'Documentation',
			description: 'To help you evaluate the possibilities offered by Dosimex-GX, you can download all the documentation associated with this code:',
			anchors: ['User manuals', 'The validation files', 'Some end of study internships reports using Dosimex'],
		},
		manuals: {
			title: 'User manuals',
			items: ['Gamma dose manual', 'Generator X-ray manual', 'Manual + Validation NF C15-160', 'Practical values in radiology'],
		},
		validations: {
			title: 'Validation files and MCNP references',
			items: ['Gamma emission validation file', 'X-ray generator validation file', 'X-ray generator reference MCNP/CEA', 'MCNP/AREVA radionuclide reference', 'X attenuation reference'],
		},
		internships: {
			title: 'End of study internships reports vs Dosimex',
			items: ['Ulysse research papers', 'Microshield vs Dosimex 1 research papers', 'Microshield vs Dosimex 2 research papers', 'Microshield vs Dosimex 3 research papers'],
		},
	},
	training: {
		videoTitle: 'Dosimex \u2014 Presentation',
		header: {
			title: 'Training',
			description: 'We offer on-site or videoconference intra-company training courses from 1 to 3 days to learn how to use Dosimex tools. These trainings are based on tutorials integrating the use of Dosimex tools in the broader framework of radiological risk analysis applied to concrete cases encountered in the industrial and medical world.',
		},
		section1: {
			title: 'Examples of topics covered, which can be modified according to the needs:',
			items: [
				'Calculation of protection around medical and industrial X-ray generators',
				'Application NF C 15-160',
				'Management of a high activity Radium source',
				'Technetium 99m syringe and operator protection',
				'Fluorine 18 contamination',
				'Co60, Ir192, Sr95, Cs137 gamma radiography',
				"EDF's preferred radionuclides",
				'ALARA approach on primary piping',
				'Diffusion in a blockhouse baffle',
				'Radiation protection around a fuel storage pool',
				'Biological protection of a Californium 252 source (neutrons + gamma)',
				'Food ionizations',
				'High activity Strontium-Yttrium 90 source',
				'Radiation protection analysis of a fission product waste package (CSDV)',
			],
		},
		section2: {
			title: 'In partnership with Veolia Nuclear Solutions, we offer other training courses on the following topics:',
			items: ['Nuclear physics and radioactivity', 'Interaction between radiation and matter', 'Decision threshold (ISO 11929)', 'Gamma spectrometry'],
			button: 'Training catalogue',
		},
		questions: {
			title: 'Any questions?',
			text: 'Feel free to contact us via the form below or by phone at 06 89 70 90 35',
			button: 'Contact us',
		},
	},
	videos: {
		header: {
			title: 'Videos',
			description: 'You will find below all the videos concerning the operational, learning and measurement packages. We also propose on our YouTube channel other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Watch our YouTube channel',
		},
		packTitle: 'Videos from the pack ',
		packOpe: { name: 'operational', label: 'operational pack' },
		packPeda: { name: 'learning', label: 'learning pack' },
		packMes: { name: 'measurement', label: 'measurement pack' },
	},
	contactForm: {
		title: 'Contact us',
		labels: {
			name: 'Name',
			email: 'Email',
			phone: 'Phone',
			company: 'Company',
			address: 'Address',
			subject: 'Subject',
			message: 'Message',
		},
		errors: {
			name: 'Please enter a name',
			email: 'Please enter a valid email',
			phone: 'Please enter a valid phone number',
			message: 'Please enter a message',
		},
		button: 'Send',
		sending: 'Sending...',
		messageSent: 'Message sent!',
		messageNotSent: 'Message not sent',
	},
	footer: {
		col1: {
			p: [
				'Copyright © 2025 Designed by Dosimex',
				'All rights reserved',
				'06 89 70 90 35',
				'Follow us on social media',
			],
		},
		col2: {
			title: 'Resources',
			p: ['Dosismart', 'Video archives', 'Manuals and validations', 'Readings'],
		},
		col3: {
			title: 'Company',
			p: ['About us', 'Legal', 'Contact'],
		},
	},
} as const
