export const en = {
	seo: {
		home: {
			title: 'Dosimex — Radiation Protection Calculation Tools',
			description: 'The Dosimex Suite (17 Excel calculation modules) and Dosismart, the Dosimex web platform: browser calculation, organization management, suite download. MCNP-validated, 30 years of experience.',
		},
		software: {
			title: 'The Dosimex Suite — 17 Calculation Modules',
			description: 'The Dosimex Suite in Excel: 6 operational codes (gamma, X-ray, beta, neutron, internal exposure, gammagraphy), 6 interactive learning modules and 5 measurement utilities. MCNP-validated, documented, proven over 30 years.',
		},
		dosismart: {
			title: 'Dosismart — the Dosimex web platform',
			description: 'Dosismart, the Dosimex web platform: gamma calculation and X-ray generator in the browser, history, source inventory, zoning plans and workstation studies. Subscribe, download the Dosimex Suite and manage your organization. Free 14-day trial.',
		},
		product: {
			title: 'Pricing — Dosimex Suite + Dosismart',
			description: 'One subscription, two tools: the Dosimex Suite (17 Excel modules) and Dosismart (web app). Base plan €500/year excl. VAT, Compliance plan €1,350/year. Free 14-day trial.',
		},
		training: {
			title: 'Radiation Protection Training — Dosimex',
			description: 'Dosimex in-house training from 1 to 3 days: hands-on calculation tools, practical exercises applied to real radiation protection cases.',
		},
		books: {
			title: 'Recommended Readings — Dosimex',
			description: 'Curated selection of reference books on radiation protection, dosimetry and nuclear physics recommended by Dosimex experts.',
		},
		manuals: {
			title: 'Documentation & Validation — Dosimex',
			description: 'User manuals, MCNP validation files and internship reports for Dosimex-GX. Complete documentation available as downloadable PDFs.',
		},
		videos: {
			title: 'Videos & Tutorials — Dosimex',
			description: 'Explanatory videos for each Dosimex tool: operational, learning and measurement packs. Visit our YouTube channel for more.',
		},
		about: {
			title: 'Our Team — Dosimex',
			description: 'Meet Gérald Lopez and Alain Vivier, the creators of Dosimex. Over 30 years of experience in radiation protection and dosimetry.',
		},
		contact: {
			title: 'Contact & Quote — Dosimex',
			description: 'Contact the Dosimex team for a quote or a demonstration of the Dosimex Suite and Dosismart. Video conference available.',
		},
		blog: {
			title: 'Blog — Dosimex',
			description: 'Articles and news on radiation protection, dosimetry and Dosimex tools.',
		},
		legal: {
			title: 'Legal Notice — Dosimex',
			description: 'Legal notice for dosimex.fr: publisher, hosting, terms of use, intellectual property and personal data.',
		},
		testimonials: {
			title: 'User Feedback — Dosimex',
			description: 'Discover feedback from Dosimex users: IRSN, EDF, ORANO, CNRS, university hospitals and other radiation protection professionals share their experience.',
		},
	},
	altText: {
		logo: 'DOSIMEX - Radiation Dosimetry Software',
		flagUk: 'UK flag - DOSIMEX available in English',
		decorativePattern: 'Decorative geometric pattern background',
		radiationSymbol: 'DOSIMEX radiation safety symbol - clover leaf icon',
		carouselMain: 'DOSIMEX radiation dosimetry software interface mockup',
		carouselScreens: 'Banner image',
		trainingMaterials: 'DOSIMEX radiation safety training course materials',
		manualCover: 'Manual cover',
		cardIcon: 'Icon',
	},
	navbar: {
		items: ['Dosimex Suite', 'Training', 'Documentation', 'Our story', 'Contact', 'Blog'],
		products: 'Software',
		dosismart: 'Dosismart',
		tarifs: 'Pricing',
	},
	home: {
		hero: {
			badge: 'New: Dosismart, the Dosimex web platform',
			title: 'Radiation protection calculation,',
			titleAccent: 'within reach of everyone',
			subtitle:
				'For 30 years, Dosimex has put calculation within reach of radiation-protection professionals — and helped them understand the physics behind it. Now on the web with Dosismart: the same validated calculations, right in your browser.',
			cta: 'Try Dosismart free — 14 days',
			trialButton: 'Contact us',
		},
		partners: {
			title: 'Partners',
			descriptions: [
				'A company that loves projects. So do we',
				'The first to use Dosimex in PCR training',
				'Partner for radiation protection training and Dosimex user',
				'The only ones in France who know how to encrypt Excel (and other Microsoft products). Without them we simply would not exist',
				'We are proud to help them in their missions',
				'Our historical editor for the book "calculation of doses generated by ionizing radiation"',
				'Use Dosimex a lot in their calculations',
				'Among the first to support us. And they continue to do so. Thank you',
				'Our long-time partner for training in gamma spectrometry and other fields',
				'They have honored us with their appreciation of our codes. And we highly recommend the RayXpert code',
			],
		},
		offers: {
			title: 'One mission: radiation-protection calculation for everyone',
			description:
				'For 30 years we have made calculation reachable — and helped people understand the physics, not just get a number. Dosismart carries that mission to the web: the same validated calculations, in your browser.',
			card1: {
				title: 'Calculate',
				description:
					'The 17 calculation modules of the Dosimex Suite, in Excel — from dose rate to zoning. MCNP-validated, each shipped with its video and validation files.',
				linkLabel: 'See the suite',
				packs: ['Operational pack', 'Learning pack', 'Measurement pack'],
			},
			card2: {
				title: 'Understand',
				description:
					'6 interactive educational modules, 13 course documents on nuclear physics and metrology, plus appendices from the reference book. To deepen your understanding of the fundamentals at your own pace.',
				linkLabel: 'See resources',
			},
			card3: {
				title: 'Train',
				description:
					'1 to 3-day training courses adapted to your specific challenges. Hands-on tool training, practical exercises on real-world cases, skill development.',
				linkLabel: 'Learn more',
			},
		},
		platform: {
			title: 'Dosismart — the Dosimex web platform',
			intro: 'Much more than a calculation tool: Dosismart is your Dosimex workspace, where you calculate in the browser, keep a traceable record, collaborate and run your organization.',
			tagline: 'Your Dosimex workspace, right in the browser.',
			deck: 'And it keeps growing: one subscription that expands with new capabilities over time.',
			highlights: ['Gamma calculation', 'History', 'Source inventory', 'Zoning plans', 'Workstation studies', 'Team work'],
			learnMore: 'Discover Dosismart',
			cta: 'Open Dosismart',
			trialNote: 'Free 14-day trial, no credit card.',
		},
		suite: {
			title: 'The Dosimex Suite — 17 calculation modules in Excel',
			subtitle: 'For <strong>30 years</strong>, the reference for operational radiation protection calculation: MCNP-validated and used by EDF, Orano, Apave and over <strong>1,500</strong> professionals. Its codes are progressively moving to Dosismart, on the web.',
			cta: 'Explore the Dosimex Suite',
			items: [
				{
					title: 'Operational pack: 6 calculation codes',
					text: 'Gamma, X-ray, beta, neutron, internal exposure, gammagraphy — the everyday calculations.',
					icon: 'calc',
					link: { label: 'See the codes', href: '/software#pack-ope' },
				},
				{
					title: 'Learning pack: 6 interactive modules',
					text: 'Photon and charged-particle interaction, ICRU 57 coefficients, counting statistics.',
					icon: 'book',
					link: { label: 'See the modules', href: '/software#pack-peda' },
				},
				{
					title: 'Measurement pack: 5 utilities',
					text: 'Gamma spectrometry (TAGE), contamination meters (Co3), decision thresholds, uncertainties, calibration lines.',
					icon: 'table',
					link: { label: 'See the utilities', href: '/software#pack-mes' },
				},
			],
		},
		close: {
			title: 'Two tools, one subscription',
			subtitle: 'The Dosimex desktop suite and the Dosismart web app — together, with technical support included.',
			bullets: ['14-day free Dosismart trial', 'Technical support included', 'No credit card required'],
			price: 'The Dosimex Suite and Dosismart',
			includes: 'one subscription, technical support included',
			pricingLink: 'See full pricing',
			dosismartNote: 'Free 14-day trial on Dosismart',
			quoteButton: 'Get Dosimex',
			trialButton: 'Try Dosismart',
		},
		packs: {
			title: 'What the Dosimex Suite contains',
			subtitle: 'Every code is validated (MCNP, RayXpert, Microshield) with full documentation included. The pack also includes 11 course documents.',
			allTools: 'See all tools in detail',
		},
		numbers: {
			items: [
				{ value: '+30 years', label: 'of experience' },
				{ value: '+1500', label: 'users in the field' },
				{ value: '17', label: 'calculation codes' },
			],
		},
		videoTitle: 'Dosimex Presentation',
		videos: {
			title: 'Join us on YouTube',
			description:
				'We offer you other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Our YouTube channel',
		},
		opinion: {
			name: 'Jean-Lionel Trolet',
			job: 'EAMEA — French Military School of Nuclear Energy Applications',
			text: 'I use DOSIMEX, which gives me total satisfaction, both by the quality of its results and its ease of use, in the training of personnel from the Ministry of the Armed Forces. It has, among other things, the strength of taking into account common situations faced by MinArm agents, both in the roles of medical PCRs (thanks to the X-ray calculation module!) as well as those involved at all levels in the industrial field (from PNR to engineer). Finally, it is so easy to use that almost all the PCRs we train have adopted it in their units.',
			button: 'More reviews',
		},
		references: {
			title: 'Publications and References',
			subtitle:
				'DOSIMEX is cited in numerous scientific publications, professional magazine articles, and research papers. Discover how our tools contribute to the advancement of research and practice in radiation protection.',
			btnText: 'View',
			internshipsText:
				'Also find end-of-study internship reports citing DOSIMEX in their methodologies.',
			internshipsBtn: 'View',
			items: [
				{
					title: 'Predictive Dose Calculation for Better Protection',
					description:
						'SIH-Solutions article about the use of DOSIMEX at Institut Curie for predicting exposures in medical radiology.',
					url: 'https://www.sih-solutions.fr/le-calcul-predictif-de-dose-pour-une-meilleure-protection',
				},
				{
					title: 'Dose Assessment: A Prerequisite for Risk Management',
					description:
						'LinkedIn post about the use of DOSIMEX in the university hospitals of Nantes and Toulouse.',
					url: 'https://www.linkedin.com/posts/sih-solutions_dosimex-activity-6940552424990380032-wsY9/?utm_source=linkedin_share&utm_medium=member_desktop_web',
				},
				{
					title: 'Study of PMMA Layer Impact on Electronic Equilibrium',
					description:
						'Studies the impact of PMMA layers on electronic equilibrium for radiation protection instrument calibration and models X/gamma beams with DOSIMEX.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324004160',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Beam Quality Definition in Medical Context',
					description:
						'Uses DOSIMEX to define beam qualities (X and gamma) in medical context and analyze the influence of PMMA thickness on calibration factors.',
					url: 'https://www.sciencedirect.com/science/article/abs/pii/S0969804324001532',
					authors: 'Talbi A. et al.',
					year: '2024',
					journal: 'Radiation Physics and Chemistry',
				},
				{
					title: 'Radiation Protection Work for Examination Cell - INB 164',
					description:
						'Radiation protection work for commissioning an examination cell: comparison/use of three codes including DOSIMEX alongside MicroShield and RayXpert.',
					url: 'https://inis.iaea.org/records/8q3yn-jja37',
					authors: 'CEDRA Study',
					year: '2018',
					journal: 'INIS - IAEA Database',
				},
				{
					title: 'Dosimetry Optimization Study - Software Validation',
					description:
						'Dosimetry optimization study; X-ray beam simulations performed with DOSIMEX (description of software validation argument).',
					url: 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4896352',
					authors: 'Zidouz T. et al.',
					year: '2025',
					journal: 'SSRN - Preprint',
				},
				{
					title: 'DOSIMEX - Radiation Protection Codes Available to Everyone',
					description:
						'Presentation article "Dosimex - radiation protection calculation codes available to everyone" (reference source on the package and its modules). Useful to cite when justifying the use of DOSIMEX in a method.',
					url: 'https://inis.iaea.org/records/xaj40-pdm79',
					authors: 'Vivier A., Lopez G.',
					year: '2016',
					journal: 'Ionizing Radiation, Measurement and Protection Techniques - INIS',
				},
			],
		},
	},
	testimonials: {
		header: {
			title: 'User feedback',
			subtitle: 'Excerpts from user feedback collected through a survey conducted in April 2018.',
			disclaimer: 'The opinions expressed here are solely those of the authors in a personal capacity and do not represent the position of their respective institutions.',
		},
		cta: {
			title: 'Convinced?',
			button: 'Request a quote',
			trialButton: 'Try Dosismart',
		},
	},
	contact: {
		header: {
			title: 'Contact us',
			subtitle: 'Quote, demonstration or technical question — the Dosimex team answers you directly, by phone or email.',
		},
		info: {
			phone: { label: 'Phone', value: '06 89 70 90 35' },
			email: { label: 'Email' },
			demo: { label: 'Demo', value: 'Video conference available' },
		},
	},
	dosismartPage: {
		hero: {
			title: 'Dosismart — the Dosimex web platform',
			subtitle: 'Your radiation protection workspace in the browser: calculate, keep a traceable record, collaborate and run your organization. A real dashboard, on any device, no installation.',
			cta: 'Open Dosismart',
			ctaSecondary: 'See pricing',
			trialNote: 'Free 14-day trial, Compliance features included. No credit card.',
		},
		whatsInside: {
			title: 'What you find in Dosismart',
			description: 'Your calculations, your radiation protection data and your team in one place.',
			items: [
				{ icon: 'calc', title: 'Calculations', text: 'Gamma calculation, X-ray generator, skyshine and shield optimizer, right in the browser. Calculations validated, just like the Dosimex Suite.' },
				{ icon: 'history', title: 'History and traceability', text: 'Every calculation is recorded and documented. Retrieve and replay your assessments.' },
				{ icon: 'team', title: 'Team work', text: 'Organizations, sharing between colleagues, access and subscription management.' },
				{ icon: 'inventory', title: 'Source inventory', text: 'Source tracking with automatic decay.', badge: 'Compliance' },
				{ icon: 'map', title: 'Zoning plans', text: '2D editor to draw your radiological zoning plans.', badge: 'Compliance' },
				{ icon: 'doc', title: 'Workstation studies', text: 'Generator for ready-to-sign regulatory documents.', badge: 'Compliance' },
			],
		},
		spotlights: {
			title: 'In detail',
			description: 'What each module actually does — rebuilt from the real Dosismart interface.',
			items: [
				{
					preview: 'history',
					eyebrow: 'Traceability',
					title: 'Every calculation, kept and replayable',
					text: 'The Excel workstation keeps nothing. Dosismart records every calculation with its full set of parameters — retrieve, replay and export any assessment, months later, exactly as it was.',
					bullets: ['Full parameter snapshot', 'CSV and PDF export', 'Naming and favorites to find them fast'],
					badge: '',
				},
				{
					preview: 'inventory',
					eyebrow: 'Inventory',
					title: 'A source inventory that keeps itself current',
					text: 'Register your sources once. Dosismart recomputes the activity every day from radioactive decay (A = A₀·e^−λt), using a library of about 200 ICRP nuclides. No more spreadsheet quietly going stale.',
					bullets: ['~200 built-in nuclides', 'Decay recomputed automatically', 'SIGIS export and source lifecycle'],
					badge: 'Compliance',
				},
				{
					preview: 'zonage',
					eyebrow: 'Zoning',
					title: 'Zoning plans that are computed, not drawn',
					text: 'Import a floor plan, place your sources: the 2D editor generates the regulatory zone overlay computed by the Dosismart engine, compliant with the French decree of 28 January 2020. PDF export with legend. Replaces Paint and Inkscape.',
					bullets: ['Dose rate computed on a grid', 'Zones per the 28/01/2020 decree', 'PDF export with regulatory legend'],
					badge: 'Compliance',
				},
				{
					preview: 'etude',
					eyebrow: 'Documents',
					title: 'Workstation studies generated, not retyped',
					text: 'The wizard pulls in your sources and plans, computes the annual dose per exposure scenario, classifies the worker (Cat A / B / non-exposed) and produces a ready-to-sign regulatory PDF.',
					bullets: ['Annual dose per scenario', 'Automatic worker classification', 'Ready-to-sign regulatory PDF'],
					badge: 'Compliance',
				},
			],
		},
		dashboard: {
			eyebrow: 'The platform',
			title: 'Your radiation protection dashboard',
			lead: 'Dosismart is the dashboard for your Dosimex subscription. You subscribe here, then download the Dosimex Excel suite, calculate right in the browser, or both — and run your organization from the same place.',
			points: [
				{ icon: 'download', title: 'Download the Dosimex Suite', text: 'The 17 Excel modules and your license key, straight from the dashboard.' },
				{ icon: 'calc', title: 'Calculate in the browser', text: 'Gamma calculation, X-ray generator, skyshine and shield optimizer, with history and traceability — without leaving the browser.' },
				{ icon: 'team', title: 'Run your organization', text: 'Members, access and subscription — one account for the whole team.' },
			],
			growTitle: 'A platform that grows richer over time',
			growText: 'With each release, the Suite’s calculation codes move into Dosismart, with the same MCNP-validated physics proven over 30 years. The Dosimex Suite stays the reference for everything the platform does not cover yet.',
			cta: 'Explore the Dosimex Suite',
		},
		cta: {
			title: 'Ready to try Dosismart?',
			text: 'Free 14-day trial, Compliance features included, no credit card. A question before you start? Let’s talk.',
			button: 'Open Dosismart',
			contact: 'Contact us',
		},
	},
	software: {
		header: {
			title: 'The Dosimex Suite',
			description:
				'For 30 years, the Dosimex Suite has brought together the reference radiation protection calculation tools in Excel: 6 operational codes, 6 learning modules and 5 measurement tools. Every code is validated (MCNP, RayXpert, Microshield) and ships with its complete documentation.',
			langNote: 'Most tools are available in French and English.',
			anchors: [
				{ label: 'Operational pack', href: '#pack-ope' },
				{ label: 'Learning pack', href: '#pack-peda' },
				{ label: 'Measurement pack', href: '#pack-mes' },
			],
		},
		included: {
			title: 'Included with the suite',
			text: 'On top of the 17 modules and their documentation: 11 course documents (nuclear physics, nuclear measurement, radiation–matter interactions, uncertainties…) and the 19 appendices of the book "Calculation of doses generated by ionizing radiation" (EDP Sciences 2016).',
		},
		prerequisites: {
			title: 'Prerequisites',
			text: 'VBA/Excel — Windows XP to 11, Excel 2003 to 2024. Virtual machine required on Mac or Linux. Dosismart, for its part, runs in the browser: no installation.',
		},
		dosismartBanner: {
			title: 'Dosismart: the evolution of the suite',
			text: 'Dosismart is the Dosimex web platform. Over the years, the calculation codes of the suite are progressively ported to it — and validated with the same rigor (MCNP, OpenMC) as the suite’s own codes. Already online: gamma calculation, X-ray generator, skyshine and shield optimizer, with calculation history and team collaboration. The suite remains the reference for everything the platform does not cover yet.',
			button: 'Try Dosismart',
		},
		packOpe: {
			title: 'Operational pack',
			description:
				'These calculation tools enable to estimate the radiological risks at their correct levels and to design the necessary protections',
			tools: [
				{
					name: 'DOSIMEX-GX 3.2 — Gamma emitters',
					description:
						'Deterministic calculation code of dose rate for gamma emitters (volumic sources, surface source…). With many options: skyshine, bremsstrahlung, zoning, build-up',
					videoId: 'oiYwIvxnxHU',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-GX 3.2 — X-ray generators',
					description:
						'Deterministic calculation code of dose rate for X-ray generators (primary and scattered beam), with NF C15-160/2018 calculation worksheet option',
					videoId: 'xriiq6v47oE',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-B 3.2',
					description:
						'Deterministic calculation code of beta emitter dose rate and monoenergetic electrons. Taking into account volumetric sources (beaker, syringe) or surface sources (skin contamination)',
					videoId: '4Cfya_rHa04',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-N 3.2',
					description:
						'Monte-Carlo calculation code of neutron emitter dose rate (Am/Be type) with biological protection (water, polyethylene, Boron, Cadmium etc.). Pedagogical module with neutron trajectory visualization',
					videoId: '7emAJHES-fw',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-I 3.2',
					description:
						'Internal exposure calculation code. In accordance with the decree of November 16, 2023. Consideration of leakage kinetics, renewal, ground deposition. Atmospheric transfer calculations',
					videoId: 'CnqQhyB6cEo',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-MN 3.2',
					description:
						'Data management utility to know the absorbed doses per unit of activity administered for ICRP 53, 80, 106 and 128 radiopharmaceuticals',
					videoId: 'sj-FVjP87jA',
					frOnly: false,
				},
				{
					name: 'DOSIMEX-GAMMAGRAPHY',
					description:
						'Tool dedicated to the calculation of zoning in gammagraphy for 4 sources: Se 75, Cs 137, Co 60 and Ir 192. Isodose and operational zoning calculations. Lead, concrete, steel, air shield',
					videoId: 'oJYfQDhBP68',
					frOnly: true,
				},
			],
		},
		packPeda: {
			title: 'Learning pack',
			description:
				'They provide a better understanding of the physics of radiation-matter interaction, which is the source of the generated doses, as well as of the protective capacities of the screens that can be used',
			tools: [
				{
					name: 'Photon Interaction 3.2',
					description:
						'Utility implementing the principles of photon-matter interactions in materials with various applications: kerma calculation, dose, mean free path, Compton effect, trajectory visualization (Monte-Carlo)',
					videoId: 'cBQ5-CiqqT4',
					frOnly: false,
				},
				{
					name: 'Charged Particles Interaction 3.2',
					description:
						'Utility implementing the principles of charged particle-matter interactions in materials with various applications: range calculation, fluence-dose coefficient, application to beta spectra',
					videoId: 'vXT2h8GJ8Qk',
					frOnly: false,
				},
				{
					name: 'Serious Game 3.2',
					description:
						'Pedagogical utility allowing to highlight the essential parameters of radiation protection: distance, time, screen, activity, radionuclide nature',
					videoId: 'pYbgwudKniA',
					frOnly: false,
				},
				{
					name: 'ICRU 57 Coefficients 3.2',
					description:
						'Utility allowing to know the fluence-dose equivalent coefficients and normalized air kerma for electrons, photons and neutrons',
					videoId: 'Ltk5x2dW_VI',
					frOnly: false,
				},
				{
					name: 'Nuclear meter',
					description:
						'Nuclear meter simulator that realistically reproduces statistical aspects, efficiency concept, uncertainties, and decision thresholds',
					videoId: 'fIEWzgTzC2g',
					frOnly: true,
				},
				{
					name: 'Radioactive decay',
					description:
						'Simulation tool for understanding the probabilistic aspects of nuclear decay: lifetime, period, fluctuation, decay law',
					videoId: 'v8RMSH0qryE',
					frOnly: true,
				},
			],
		},
		packMes: {
			title: 'Measurement pack',
			description: 'Utilities related to the measurement of ionizing radiation',
			tools: [
				{
					name: 'TAGE code (Total Absorption Gamma Efficiency)',
					description:
						'Deterministic code calculating the total absorption efficiency in gamma spectrometry, with dead layer correction (characterization), coincidence correction and efficiency of sum peaks',
					videoId: 'vSI75UZ_9UQ',
					frOnly: false,
				},
				{
					name: 'Co3 code',
					description:
						'Code for calculating the Conversion Coefficient of Contaminameters allowing to calculate the efficiency (Bq/cm2/cps) of various instruments and to obtain the surface activities versus the nature of the probe and the isotopic spectrum measured',
					videoId: '2Mq-TR8cG-o',
					frOnly: false,
				},
				{
					name: 'Random variables composition',
					description:
						'Utility allowing to combine up to 5 variables of different types by Monte-Carlo method. Accompanied by complete course documents on the subject of uncertainty calculations',
					frOnly: false,
				},
				{
					name: 'Decision threshold calculation',
					description:
						'Utility to determine the decision threshold and the detection limit in nuclear measurement. Accompanied by course materials',
					videoId: 'aA4QUutuaJc',
					frOnly: false,
				},
				{
					name: 'Calibration line',
					description:
						'Tool for constructing a calibration curve that takes into account uncertainties in the standards. With a set of tests: analysis of variance, non-regression test. With inverse Bayesian projection, decision threshold calculation, and detection limit',
					frOnly: true,
				},
			],
		},
		more: {
			title: 'More resources',
			links: [
				{ label: 'X-ray generator validation', href: '/Folders/extrait_validation_géné_X.pdf', pdf: true },
				{ label: 'Complete validation files', href: '/manuals#validations' },
				{ label: 'Gamma source validation extracts', href: '/Folders/extrait_validation_gamma.pdf', pdf: true },
				{ label: 'Dosimex-GX user manuals', href: '/manuals#manuals' },
				{ label: "What's new in Dosimex-GX 3.2", href: '/Folders/Modification_Dosimex GX_3.0.pdf', pdf: true },
				{ label: 'Our reading selection', href: '/books' },
			],
		},
		ask: {
			title: 'Any questions?',
			text: 'For a quote or to try Dosismart, contact us here or by phone at 06 89 70 90 35',
			labelButton: 'Contact us',
		},
		watchVideo: 'Watch video on YouTube',
		videosButton: 'Check out all videos',
	},
	product: {
		title: 'One subscription, two tools',
		schemaDescription: 'Annual subscription — Dosimex Suite + Dosismart',
		buttonKnowMore: 'Read more',
		description:
			'The Dosimex Suite in Excel and Dosismart, the web platform — one annual subscription, technical support included.',
		trialBanner: {
			title: 'Try Dosismart free for 14 days',
			text: 'The trial covers the full Dosismart web application, Compliance features included: calculations, source inventory, zoning plans, workstation studies. The Dosimex Suite (Excel) requires the paid subscription. No credit card.',
			button: 'Start trial',
		},
		pricing: {
			title: 'Pricing',
			packageTitle: 'Two plans. Each covers both tools: the Dosimex Suite and Dosismart.',
			suiteLink: 'The Suite in detail',
			dosismartLink: 'Dosismart in detail',
			coexistence: "New capabilities ship on Dosismart first. The Dosimex Suite remains the reference for what the web app doesn't cover yet.",
			base: {
				title: 'Base plan',
				price: '\u20AC500 excl. VAT',
				duration: 'per year',
				alt: 'or €1,000 excl. VAT for 3 years',
				tagline: 'The same price as before — now for both tools',
				features: [
					'The complete Dosimex Suite: 17 calculation modules in Excel',
					'Dosismart: gamma calculation, X-ray generator, skyshine, cylinder shield optimizer',
					'Calculation history, team collaboration, any device',
					'Technical support included',
				],
			},
			compliance: {
				title: 'Compliance plan',
				price: '\u20AC1,350 excl. VAT',
				duration: 'per year',
				alt: 'or \u20AC2,700 excl. VAT for 3 years',
				tagline: 'The regulatory documents required of the RPO, on top of the Base plan',
				features: [
					'Everything in the Base plan',
					'Source inventory with automatic decay',
					'Zoning plans editor (2D)',
					'Workstation exposure studies generator (\u00E9tudes de poste)',
				],
			},
			enterprise: {
				title: 'Enterprise plan',
				price: 'Custom pricing',
				tagline: 'Specific needs? Contact us for a tailored plan and dedicated support',
				features: [
					'Everything in the Compliance plan',
					'Priority support',
					'Custom onboarding',
					'Tailored contract & pricing',
				],
			},
			orderTitle: 'How to order?',
			orderText:
				'Request your personalized quote using the form below. We will respond promptly with your quote and payment terms.',
			quoteButton: 'Request a quote',
			subscribeButton: 'Subscribe on Dosismart',
			quoteSecondary: 'or request a quote by email',
			enterpriseButton: 'Contact us for a quote',
			directNote:
				"Subscribe directly on Dosismart: secure payment by card or by invoice (purchase order). If you'd rather talk it through first, request a quote by email.",
			explainer: {
				title: 'How it works',
				items: [
					{
						title: 'Create your Dosismart account',
						text: 'Dosismart is the Dosimex web platform. Create your account and start a free 14-day trial — the full web application, Compliance features included. No credit card.',
					},
					{
						title: 'Subscribe, then download the Suite',
						text: 'Once you subscribe, download the Dosimex Suite — 17 calculation modules in Excel. The Suite is available with the paid subscription only.',
					},
					{
						title: 'Use both, as your work requires',
						text: 'The Dosimex Suite is the reference for the full breadth of calculations; Dosismart keeps growing and will progressively enrich it. One subscription covers both.',
					},
				],
			},
		},
		trialNote: 'The 14-day free trial covers the full Dosismart web application, Compliance features included. The Dosimex Suite (Excel) requires the paid subscription.',
		faq: {
			title: 'Frequently Asked Questions',
			questions: [
				{
					question: 'What is the difference between the Dosimex Suite and Dosismart?',
					answer:
						"The Dosimex Suite includes the 17 calculation modules in Excel (gamma, X-ray, beta, neutron, internal exposure, measurement). Dosismart is the Dosimex web platform: it is where you subscribe, download the suite and manage your organization — and it is also a calculation tool in the browser (gamma calculation, X-ray generator, skyshine, shield optimizer, history, team collaboration), with source inventory, zoning plans and workstation studies in the Compliance plan. A single subscription covers everything. New capabilities ship on Dosismart first; the Suite remains the reference for what web calculation doesn't cover yet.",
				},
				{
					question: 'I have a current license (purchased since 2025) — how do I access Dosismart?',
					answer:
						'Contact us at alain.vivier@dosimex.fr: we will activate your Dosismart access. No new purchase is needed — your current license covers both tools.',
				},
				{
					question: 'I bought Dosimex before 2025 — is my license still valid?',
					answer:
						'Yes, for life, and that does not change: your perpetual license remains valid and your suite keeps working as is. Dosismart, however, requires the subscription (€500/year excl. VAT), which covers both tools.',
				},
				{
					question: 'How does the free trial work?',
					answer:
						'The trial is free for 14 days, with no commitment and no credit card. It covers the full Dosismart web application, including the Compliance features. The Dosimex Suite (Excel) requires the paid subscription, which then covers both tools.',
				},
				{
					question: 'What are the prerequisites?',
					answer:
						'The Dosimex Suite: Excel 2003 to 2024, Windows (virtual machine on Mac/Linux). Dosismart: modern web browser (Chrome, Firefox, Edge, Safari), any OS, no installation.',
				},
			],
		},
		contact: {
			title: 'Quote, demo, questions?',
			text: 'Contact the Dosimex team via the form below or by phone at ',
			phone: '06 89 70 90 35',
		},
	},
	about: {
		header: {
			title: 'Our team',
			subtitle:
				'Two radiation-protection specialists — from the French Navy and Air Force to the CEA and Orano — with over thirty years of combined field experience behind Dosimex.',
		},
		timelineTitle: 'Career at Orano La Hague',
		gerald: {
			path: ['French Navy', 'EAMEA', 'Cherbourg Arsenal', 'Orano La Hague'],
			intro: [
				'I began my career in 1997 in the French Navy as an electrical technician on weapons systems. After training as a radiation protection technician (RT), I joined the RPD at Ile Longue, with various missions focused on nuclear-armed ballistic missile submarines (SNLE): radiological assistance, reactor compartment mapping, radiological analyses in the medium activity laboratory, nuclear safety exercises…',
				"In 2003, after training as a senior technician in radiation protection (TRS) at the INSTN, I joined the Ecole des Applications Militaire à l'Energie Atomique (EAMEA) where I taught radioactivity, radiation protection, dosimetry, and nuclear measurement. From that time on, to compensate for the obvious lack of tools, I started to create my own calculation tools in order to carry out simple and fast tutorials as part of my teaching.",
				'In 2010, I joined the RDP of the Cherbourg Arsenal in charge of the 2SNM (Marine Nuclear Monitoring System), a system linked to the National Measurement Network (NMN). This experience allowed me, among other things, to create the Dosimex-I code, particularly on the atmospheric transfer option.',
				"Since 2013, after having published in collaboration with Alain Vivier the book 'Calculation of dose generated by ionizing radiation', I joined the radiation protection department of the Orano site at La Hague where I was confronted with most of the site's radiation protection problems:",
			],
			timeline: [
				{ period: '2013 – 2015', text: 'Monitoring of the dismantling of the UP2-400 production unit in the High Activity sector. Specific follow-up of the dismantling worksite of a fuel dissolver type UNGG.' },
				{ period: '2015 – 2017', text: 'Dismantling advisor on the ELAN2B and STE2 (Effluent Treatment Station) perimeters, analysis of approaches.' },
				{ period: '2017 – 2018', text: 'Responsible for the radiation protection level of the High Activity perimeter of the UP2-400 plant.' },
				{ period: '2018 – 2019', text: 'Activity manager for the Conditioning Operational Unit: vitrification (R7/T7), waste treatment (AD2 and AD1/BDH) and hull compaction (ACC) workshops at the UP2-800 and UP3 plants at the La Hague site.' },
				{ period: '2019', text: "Took over responsibility for the expertise division in charge, with a team, of technical support and innovation for all the sector's activities in the fields of radiation protection and conventional safety. Acquired solid experience in the area of mixed asbestos and radiological risks." },
			],
			outro:
				'In most of the radiation protection problems I had to face, the Dosimex tools were very useful to analyze the radiological risk. Conversely, feedback has allowed me to enrich these codes.',
		},
		alain: {
			path: ['French Air Force', 'CEA', 'INSTN', 'Dosimex'],
			paragraphs: [
				"After studying at the Ecole de l'Air (class of '80) and being assigned to a Mirage IV maintenance unit, I was designated to be a PCR for X-rays on canopies. Apart from the X-ray generator, I had neither a radiation meter nor any calculation tools at the time, so I had no idea of the radiological risk involved. This experience undoubtedly sowed the seeds for the future.",
				'In 1990, I joined the Ecole Atomique de Cherbourg to do an atomic engineering degree. I was lucky enough to be able to stay there as a teacher.',
				"Responsible for teaching nuclear physics and a measurement laboratory, I began to understand the phenomena of radiation-matter interaction and realized that it should be possible to calculate, not just measure, a dose rate from a 1 GBq source of Cesium 137 placed at 1 m. My assistant, a TRS by training, answered me: 'yes, it is possible, it is called dosimetry'. I understood, through this anecdote, that this subject was not sufficiently taught in the training courses.",
				"My first modeling experience involved the calculation of the stopping power of charged particles, using Bethe's formula (see Appendix E). I was then struck by the agreement between the theoretical prediction and the results of measurements with conversion electrons and thin copper targets. This cross validation between modeling and measurement, one reinforcing the other, was a revelation.",
				"In 1998, I joined the CEA, first at the RDP in Cadarache at the AtPu (plutonium workshop), then in 2000, at the INSTN in Saclay. The first training course I created there was entitled 'dosimetry of ionizing radiation'.",
				'During visits to the Ecole Atomique, I met Gérald Lopez. I quickly recognized his skills in modeling, his capacity for analysis associated with an extraordinary work capacity. At that time, he had already laid the foundations for what would become Dosimex-GX.',
				'In 2010, when EDP agreed to publish a book on dose calculations, it became clear to me that such a book should be accompanied by calculation utilities, and especially that Gérald Lopez was essential to the realization of this project. This is how Dosimex was born.',
			],
		},
		epilogue: 'Epilogue: it is thanks to Dosimex that I was finally able, 25 years later, to have an idea of the radiological risk incurred with X-ray generators, a risk that is far from negligible.',
		cta: {
			title: 'The tools born from this story',
			text: 'Thirty years of field experience, distilled into a proven, validated radiation-protection calculation suite.',
			button: 'Discover Dosimex',
		},
	},
	books: {
		header: { title: 'Readings' },
		viewBook: 'View book',
		coverAlt: 'Cover:',
		byAuthor: 'by',
		items: [
			{ extract: 'This book is intended for students studying for careers in the nuclear industry, nuclear medicine or research. Users of ionizing radiation will also find useful and up-to-date information.', author: 'Arnaud Boquet', title: 'Radiation Protection of Workers, Patients and the Public' },
			{ extract: 'This book has two complementary objectives: to provide the reader an understanding of the physical principles at work when a target is exposed to ionizing radiation, and to propose simple calculation tools to evaluate the absorbed doses.', author: 'Alain Vivier and Gérald Lopez', title: 'Calculation of Doses Generated by Ionizing Radiation' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of unsealed sources and sealed sources necessary for their control.', author: 'Hugues Bruchet', title: 'RPC — Radiation Protection Principles and Regulations' },
			{ extract: 'The role of the competent person in radiation protection (PCR) has developed widely in recent years. This volume is intended for PCRs or future PCRs involved in medical sector facilities.', author: 'Hugues Bruchet, Amélie Roué et Christine Jimonet', title: 'RPC — Medical Sector' },
			{ extract: 'This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of X-ray generators and sealed sources.', author: 'Jean-Claude Moreau and Marc Ammerich', title: 'RPC — Industry and Research Sector' },
			{ extract: 'It was time to retrace the history of nuclear physics. Bernard Fernandez takes you by the hand to guide you through the meanders of a complicated but fascinating science.', author: 'Bernard Fernandez', title: 'From Atom to Nucleus — A Historical Approach to Nuclear Physics' },
			{ extract: "Intended for a wide audience, Le monde subatomique describes the evolution of ideas about the interactions and constituents of matter, from the discovery of the neutron to that of the Z° boson.", author: 'Luc Valentin', title: 'The Subatomic World' },
			{ extract: 'This book aims to synthesize many years of experience in the field of external dosimetry and protection techniques against this type of exposure in the industrial, research and medical fields.', author: 'Rodolphe Antoni et Laurent Bourgois', title: 'Shielding Techniques and Radiation Protection' },
			{ extract: 'This book reviews the state of the art in dosimetric calculations, ionizing radiation metrology and radiation protection through problems related to concrete applications in the field.', author: 'Laurent Bourgois and Rodolphe Antoni', title: 'Dosimetry of Ionizing Radiation and Radiation Protection' },
			{ extract: 'Radioactivity is everywhere, it surrounds us. This book, without complex mathematical formulas, will allow all readers to better understand the role and the work of radiation protectionists.', author: 'Marc Ammerich', title: 'Radioactivity Under Surveillance' },
			{ extract: 'These books are adapted to students in master radiation protection, engineering school but also to students specialized in BTS or license radiation protection.', author: 'Marc Ammerich', title: 'Radiation Protection Exercises — Volume 1' },
		],
	},
	manuals: {
		header: {
			title: 'Documentation',
			description: 'To help you evaluate the possibilities offered by Dosimex-GX, you can download all the documentation associated with this code:',
			anchors: ['User manuals', 'The validation files', 'Some end of study internships reports using Dosimex'],
		},
		manuals: {
			title: 'User manuals',
			items: ['Gamma dose manual', 'Generator X-ray manual', 'Manual + Validation NF C15-160', 'Practical values in radiology'],
		},
		validations: {
			title: 'Validation files and MCNP references',
			items: ['Gamma emission validation file', 'X-ray generator validation file', 'X-ray generator reference MCNP/CEA', 'MCNP/AREVA radionuclide reference', 'X attenuation reference'],
		},
		internships: {
			title: 'End of study internships reports vs Dosimex',
			items: ['Ulysse research papers', 'Microshield vs Dosimex 1 research papers', 'Microshield vs Dosimex 2 research papers', 'Microshield vs Dosimex 3 research papers'],
		},
	},
	training: {
		videoTitle: 'Dosimex \u2014 Presentation',
		header: {
			title: 'Training',
			description: 'We offer on-site or videoconference intra-company training courses from 1 to 3 days to learn how to use Dosimex tools. These trainings are based on tutorials integrating the use of Dosimex tools in the broader framework of radiological risk analysis applied to concrete cases encountered in the industrial and medical world.',
		},
		section1: {
			title: 'Examples of topics covered, which can be modified according to the needs:',
			items: [
				'Calculation of protection around medical and industrial X-ray generators',
				'Application NF C 15-160',
				'Management of a high activity Radium source',
				'Technetium 99m syringe and operator protection',
				'Fluorine 18 contamination',
				'Co60, Ir192, Sr95, Cs137 gamma radiography',
				"EDF's preferred radionuclides",
				'ALARA approach on primary piping',
				'Diffusion in a blockhouse baffle',
				'Radiation protection around a fuel storage pool',
				'Biological protection of a Californium 252 source (neutrons + gamma)',
				'Food ionizations',
				'High activity Strontium-Yttrium 90 source',
				'Radiation protection analysis of a fission product waste package (CSDV)',
			],
		},
		section2: {
			title: 'In partnership with Veolia Nuclear Solutions, we offer other training courses on the following topics:',
			items: ['Nuclear physics and radioactivity', 'Interaction between radiation and matter', 'Decision threshold (ISO 11929)', 'Gamma spectrometry'],
			button: 'Training catalogue',
		},
		questions: {
			title: 'Any questions?',
			text: 'Feel free to contact us via the form below or by phone at 06 89 70 90 35',
			button: 'Contact us',
		},
	},
	videos: {
		header: {
			title: 'Videos',
			description: 'You will find below all the videos concerning the operational, learning and measurement packages. We also propose on our YouTube channel other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Watch our YouTube channel',
		},
		packTitle: 'Videos from the pack ',
		packOpe: { name: 'operational', label: 'operational pack' },
		packPeda: { name: 'learning', label: 'learning pack' },
		packMes: { name: 'measurement', label: 'measurement pack' },
	},
	contactForm: {
		title: 'Contact us',
		labels: {
			name: 'Name',
			email: 'Email',
			phone: 'Phone',
			company: 'Company',
			address: 'Address',
			subject: 'Subject',
			message: 'Message',
		},
		errors: {
			name: 'Please enter a name',
			email: 'Please enter a valid email',
			phone: 'Please enter a valid phone number',
			message: 'Please enter a message',
		},
		button: 'Send',
		sending: 'Sending...',
		messageSent: 'Message sent!',
		messageNotSent: 'Message not sent',
	},
	footer: {
		col1: {
			p: [
				'Copyright © 2026 Designed by Dosimex',
				'All rights reserved',
				'06 89 70 90 35',
				'Follow us on social media',
			],
		},
		col2: {
			title: 'Resources',
			p: ['Dosismart', 'Video archives', 'Manuals and validations', 'Readings'],
		},
		col3: {
			title: 'Company',
			p: ['About us', 'Legal', 'Contact'],
		},
		manageCookies: 'Manage cookies',
	},
} as const
