import ILang from './interface'

const text: ILang = {
	altText: {
		logo: 'DOSIMEX - Radiation Dosimetry Software',
		flagUk: 'UK flag - DOSIMEX available in English',
		decorativePattern: 'Decorative geometric pattern background',
		radiationSymbol: 'DOSIMEX radiation safety symbol - clover leaf icon',
		carouselMain: 'DOSIMEX radiation dosimetry software interface mockup',
		carouselScreens: 'Banner image',
		trainingMaterials: 'DOSIMEX radiation safety training course materials',
		manualCover: 'Manual cover',
		cardIcon: 'Icon',
	},
	Home: {
		header: {
			title: 'DOSIMEX - The Professional Excel Suite for Radiation Protection Calculations',
			p: 'A set of practical, easy-to-use, validated calculation tools that address many situations encountered in radiation protection. They will allow you to improve your expertise level.',
			promo: 'Most of our calculation tools are available in English and French.',
			button: 'Discover',
			textImage: [
				'Dosimex-B Beta emission',
				'Dosimex-GX X-ray Generator',
				'Dosimex-GX Radionuclide',
				'Dosimex-N Monte-Carlo neutron',
			],
		},
		partners: {
			title: 'Partners',
			li: [
				'A company that loves projects. So do we',
				'The first to use Dosimex in PCR training',
				'Partner for radiation protection training and Dosimex user',
				'The only ones in France who know how to encrypt Excel (and other Microsoft products). Without them we simply would not exist',
				'We are proud to help them in their missions',
				'Our historical editor for the book  « calculation of doses generated by ionizing radiation »',
				'Use Dosimex a lot in their calculations',
				'Among the first to support us. And they continue to do so. Thank you',
				'Our long-time partner for training in gamma spectrometry and other fields',
				'They have honored us with their appreciation of our codes. And we highly recommend the RayXpert code',
			],
		},
		offers: {
			title: 'What we offer',
			p: 'A set of calculation tools (total of 17) covering most of the field in radiation protection: gamma, beta and neutron external exposure, internal exposure, atmospheric transfer and more. You will find on this site explanatory videos for each tool and their validation files (downloadable pdf).',
			card1: {
				title: 'Software packs',
				p: 'Find all Dosimex utilities with specific videos: operational pack, learning pack, measurement pack',
			},
			card2: {
				title: 'Documentation',
				p: 'Validated via MCNP, RayXpert, Microshield and Mercurad. Access all documentation associated with Dosimex-GX',
			},
			card3: {
				title: 'Formations',
				p: 'We guide you to take in hand these calculation tools by adapting us to your specific problems',
			},
		},
		numbers: {
			number1: '+30 years',
			p1: ' of experience',
			number2: '+1000',
			p2: 'convinced radioprotectionists',
			number3: '35',
			p3: 'days of support provided',
		},
		videos: {
			title: 'Join us on YouTube',
			p: 'We offer you other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Check out the other videos',
		},
		opinion: {
			name: 'Jean-Lionel Trolet',
			job: 'EAMEA',
			opinion:
				'I use DOSIMEX, which gives me total satisfaction, both by the quality of its results and its ease of use, in the training of personnel from the Ministry of the Armed Forces. It has, among other things, the strength of taking into account common situations faced by MinArm agents, both in the roles of medical PCRs (thanks to the X-ray calculation module!) as well as those involved at all levels in the industrial field (from PNR to engineer). Finally, it is so easy to use that almost all the PCRs we train have adopted it in their units.',
			btn: 'More reviews',
		},
		callToAction: {
			title: 'Get your Dosimex license today by requesting a quote',
			button: 'Get Dosimex',
		},
		videoLink: {
			pres: 'q9QXG78ciXY',
		},
	},
	Software: {
		header: {
			title: 'Product',
			p: 'The DOSIMEX pack is your reference digital solution for all radiation protection calculations. It includes 17 utilities: precise and reliable codes for operational calculations, clear, rich, and interactive educational modules, and tools covering measurement aspects. Designed to be fast, reliable, and easy to use, DOSIMEX becomes an indispensable tool for saving time, working safely, and achieving accurate results.',
			li: ['Operational pack', 'Learning pack', 'Measurement pack'],
		},
		button: {
			label: 'Check out all videos',
		},
		linkVideo: 'Watch the video on YouTube',
		packOpe: {
			title: 'Operational pack',
			descrip:
				'These calculation tools enable to estimate the radiological risks at their correct levels and to design the necessary protections',
			liTitles: [
				'DOSIMEX-GX 3.1',
				'DOSIMEX-B 3.0',
				'DOSIMEX-N 3.0',
				'DOSIMEX-I 3.0',
				'DOSIMEX-MN 1.0',
				'DOSIMEX-GAMMAGRAPHY',
			],
			li: [
				'deterministic calculation code of dose rate for [gamma emitters](https://www.youtube.com/watch?v=oiYwIvxnxHU ) (volumics sources, surface source...) and [X-ray generators](https://www.youtube.com/watch?v=xriiq6v47oE ) (primary and scattered beam). With many options: skyshine, bremmstrhralung, zoning, build-up...',
				'[deterministic calculation code](https://www.youtube.com/watch?v=4Cfya_rHa04) of beta emitter dose rate and monoenergetic electrons. Taking into account volumetric sources (beaker, syringe) or surface sources (skin contamination)',
				'[Monte-Carlo calculation code](https://www.youtube.com/watch?v=7emAJHES-fw) of neutron emitter dose rate (Am/Be type) with biological protection (water, polyethylene, Boron, Cadmium etc..). Pedagogical module with neutron trajectory visualization',
				'[internal exposure calculation code](https://www.youtube.com/watch?v=4Cfya_rHa04). In accordance with the decree of November 16, 2023. Consideration of leakage kinetics, renewal, ground deposition. Atmospheric transfer calculations',
				'[data management utility](https://www.youtube.com/watch?v=sj-FVjP87jA) to know the absorbed doses per unit of activity administered for ICRP 53, 80, 106 and 128 radiopharmaceuticals',
				'[tool dedicated to the calculation of zoning in gammagraphy](https://youtu.be/oJYfQDhBP68) for 4 sources: Se 75, Cs 137, Co 60 and Ir 192. Isodose and operational zoning calculations. Lead, concrete, steel, air shield',
			],
		},
		packPeda: {
			title: 'Learning pack',
			descrip:
				'They provide a better understanding of the physics of radiation-matter interaction, which is the source of the generated doses, as well as of the protective capacities of the screens that can be used',
			liTitles: [
				'Photon Interaction 3.0',
				'Charged particles Interaction 3.0',
				'Serious Game 3.0',
				'ICRU 57 coefficients 3.0',
				'Nuclear meter',
				'Radioactive decay',
			],
			li: [
				'[utility](https://www.youtube.com/watch?v=cBQ5-CiqqT4) implementing the principles of photon-matter interactions in materials with various applications: kerma calculation, dose, mean free path, Compton effect, trajectories visualization (Monte-Carlo)',
				'[utility](https://www.youtube.com/watch?v=vXT2h8GJ8Qk) implementing the principles of charged particle-matter interactions in materials with various applications: range calculation, fluence-dose coefficient, application to beta spectra',
				'[utility](https://www.youtube.com/watch?v=pYbgwudKniA) with pedagogical vocation allowing to highlight the essential parameters of the radioprotection: distance, time, screen, activity, radionuclide nature',
				'[utility](https://www.youtube.com/watch?v=Ltk5x2dW_VI) allowing to know the fluence-dose equivalent coefficients and normalized air kerma for electrons, photons and neutrons',
				'[nuclear meter simulator](https://youtu.be/oJYfQDhBP68) that realistically reproduces statistical aspects, efficiency concept, uncertainties, and decision thresholds',
				'[simulation tool for understanding the probabilistic aspects of nuclear decay](https://youtu.be/v8RMSH0qryE): lifetime, period, fluctuation, decay law, etc',
			],
		},
		packMes: {
			title: 'Measurement pack',
			descrip: 'Utilities related to the measurement of ionizing radiation',
			liTitles: [
				'TAGE code (Total Absorption Gamma Efficiency)',
				'Co3 code',
				'Random variables composition',
				'Decision threshold calculation',
				'Calibration line',
			],
			li: [
				'[deterministic code](https://www.youtube.com/watch?v=vSI75UZ_9UQ) calculating the total absorption efficiency in gamma spectrometry, with dead layer correction (characterization), coincidence correction and efficiency of sum peaks',
				'[code](https://www.youtube.com/watch?v=2Mq-TR8cG-o) for calculating the Conversion Coefficient of Contaminameters allowing to calculate the efficiency (Bq/cm2/ cps) of various ictometers and to obtain the surface activities versus the nature of the probe and the isotopic spectrum measured',
				'utility allowing to combine up to 5 variables of different types by Monte-Carlo method. This utility is accompanied by complete course documents on the subject of uncertainty calculations',
				'[utility](https://www.youtube.com/watch?v=aA4QUutuaJc) to determine the decision threshold and the detection limit in nuclear measurement. This utility is accompanied by the course materials',
				'tool for constructing a calibration curve that takes into account uncertainties in the standards. With a set of tests: analysis of variance, non-regression test, etc. With inverse Bayesian projection, decision threshold calculation, and detection limit',
			],
		},
		more: {
			title: 'More resources',
			links: [
				'Dosimex-GX user manuals to discover all its possibilities',
				'complete validation files',
				'gamma source validation extracts',
				'X-ray generator validation',
				"What's new in Dosimex-GX 3.0",
				'Our reading selection',
			],
		},
		ask: {
			title: 'Any questions ?',
			text: 'For a quotation, please contact us here or by phone at 06 89 70 90 35',
			labelButton: 'Contact us',
		},
	},
	About: {
		header: {
			title: 'Our team',
		},
		gerald: {
			p: [
				'I began my career in 1997 in the French Navy as an electrical technician on weapons systems. After training as a radiation protection technician (RT), I joined the RPD at Ile Longue, with various missions focused on nuclear-armed ballistic missile submarines (SNLE): radiological assistance, reactor compartment mapping, radiological analyses in the medium activity laboratory, nuclear safety exercises...',
				"In 2003, after training as a senior technician in radiation protection (TRS) at the INSTN, I joined the Ecole des Applications Militaire à l'Energie Atomique (EAMEA) where I taught radioactivity, radiation protection, dosimetry, and nuclear measurement. From that time on, to compensate for the obvious lack of tools, I started to create my own calculation tools in order to carry out simple and fast tutorials as part of my teaching.",
				'In 2010, I joined the RDP of the Cherbourg Arsenal in charge of the 2SNM (Marine Nuclear Monitoring System), a system linked to the National Measurement Network (NMN). This experience allowed me, among other things, to create the Dosimex-I code, particularly on the atmospheric transfer option.',
				"Since 2013, after having published in collaboration with Alain Vivier, the book 'Calculation of dose generated by ionizing radiation', I joined the radiation protection department of the Orano site at La Hague where I was confronted with most of the site's radiation protection problems:",
				'In most of the radiation protection problems I had to face, the Dosimex tools were very useful to analyze the radiological risk. Conversely, feedback has allowed me to enrich these codes.',
			],
			pBorder: [
				'2013 - 2015: monitoring of the dismantling of the UP2-400 production unit in the High Activity sector. Specific follow-up of the dismantling worksite of a fuel dissolver type UNGG.',
				'2015 - 2017: dismantling advisor on the ELAN2B and STE2 (Effluent Treatment Station) perimeters, analysis of approaches.',
				'2017 - 2018: responsible for the radiation protection level of the High Activity perimeter of the UP2-400 plant.',
				'2018 - 2019: activity manager for the Conditioning Operational Unit: vitrification (R7/T7), waste treatment (AD2 and AD1/BDH) and hull compaction (ACC) workshops at the UP2-800 and UP3 plants at the La Hague site.',
				"In 2019 finally, I took over responsibility for the expertise division in charge, with a team, of technical support and innovation for all the sector's activities in the fields of radiation protection and conventional safety. At the same time, I acquired solid experience in the area of mixed asbestos and radiological risks.",
			],
		},
		alain: {
			p: [
				"After studying at the Ecole de l'Air (class of '80) and being assigned to a Mirage IV maintenance unit, I was designated to be a PCR for X-rays on canopies. Apart from the X-ray generator, I had neither a radiation meter nor any calculation tools at the time, so I had no idea of the radiological risk involved. This experience undoubtedly sowed the seeds for the future",
				'In 1990, I joined the Ecole Atomique de Cherbourg to do an atomic engineering degree. I was lucky enough to be able to stay there as a teacher.',
				"Responsible for teaching nuclear physics and a measurement laboratory, I began to understand the phenomena of radiation-matter interaction and realized that it should be possible to calculate, not just measure, a dose rate from a 1 GBq source of Cesium 137 placed at 1 m. My assistant, a TRS by training, answered me: 'yes, it is possible, it is called dosimetry'. I understood, through this anecdote, that this subject was not sufficiently taught in the training courses.",
				"My first modeling experience involved the calculation of the stopping power of charged particles, using Bethe's formula (see Appendix E). I was then struck by the agreement between the theoretical prediction and the results of measurements with conversion electrons and thin copper targets. This cross validation between modeling and measurement, one reinforcing the other, was a revelation.",
				"In 1998, I joined the CEA, first at the RDP in Cadarache at the AtPu (plutonium workshop), then in 2000, at the INSTN in Saclay. The first training course I have created there was entitled 'dosimetry of ionizing radiation'.",
				'During visits to the Ecole Atomique, I met Gérald Lopez. I quickly recognized his skills in modeling, his capacity for analysis associated with an extraordinary work capacity. At that time, he had already laid the foundations for what would become Dosimex-GX.',
				'In 2010, when EDP agreed to publish a book on dose calculations, it became clear to me that such a book should be accompanied by calculation utilities, and especially that Gérald Lopez was essential to the realization of this project. This is how Dosimex was born.',
			],
		},
		epilogue:
			'Epilogue: it is thanks to Dosimex that I was finally able, 25 years later, to have an idea of the radiological risk incurred with X-ray generators, a risk that is far from negligible',
	},
	Books: {
		header: {
			title: 'Readings',
		},
		books: [
			{
				extract: `This book is intended for students studying for careers in the nuclear industry, nuclear medicine or research. Users of ionizing radiation, operators, technicians, engineers, radiation protection officers and occupational physicians will also find useful and up-to-date information. More broadly, anyone with an interest in science will have a comprehensive overview of the phenomena related to radioactivity and ionizing radiation. This book offers courses in nuclear physics, from the constituents of matter to the interactions between radiation and matter; courses in radiation protection, including dosimetry, detection, and means of protection against exposure to ionizing radiation; and updated regulations related to radiation protection. A complete overview of nuclear culture is provided, from the history to the use of radioactivity and ionizing radiation, including their biological effects, accidents and public exposure. \n
				 For each chapter, application exercises and answers are provided. They allow the reader to understand the quantitative aspect of radiation protection, by studying contamination, personnel exposure and activity calculations. \n
				Thus, each reader could benefit from it... A high school student will find clear and up-to-date information; a BTS or professional license student will have all the basics for his courses in the same book, with training exercises; an engineering school or master's student will have a complete overview of the entire spectrum of radiation protection and the associated calculation methods; a nuclear worker will have precise information on the topic that interests him; a PCR will have all the data and formulas necessary for his missions in a single book, and a course support for PCR training. `,
				author: 'Arnaud Boquet',
			},
			{
				extract: `This book has two complementary objectives: first, to provide the reader an understanding of the physical principles at work when a target is exposed to ionizing radiation: heavy ions, electrons, photons or neutrons, and second, to propose simple calculation tools to evaluate the absorbed doses for all of these various types of radiation.
				Following this logic, the first parts are devoted to establish the physical models allowing to calculate the energy deposits according to the characteristics of the target and the radiation field. This purely physical approach applies to any type of irradiated medium, inert or living, resulting in a particular physical quantity: the absorbed dose.
				The work then focuses on a particular target, the human being, and is interested in the radiometric quantities used in radiation protection, equivalent doses and effective doses, particular quantities translating the biological response of an individual exposed to ionizing radiation. By specifying the sources and the conditions of irradiation, it is then possible to establish the link between the activity of a radioactive source and the risk incurred by an individual exposed to this source, in external as well as internal irradiation. These same principles and models allow finally to evaluate the means of protection against these various radiations as well as the principles and the main methods used to measure these regulatory dosimetric quantities.`,
				author: 'Alain Vivier and Gérald Lopez',
			},
			{
				extract: `This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of unsealed sources and sealed sources necessary for their control. In accordance with the regulatory requirements stipulating that this module must allow the application of the knowledge acquired during theoretical training to concrete work situations that may be encountered, it includes 8 chapters dealing with the following aspects
				- radiation protection in industrial and research facilities: use of sources and associated risks, layout of premises, exposure assessment, radiation protection controls
				- the use of devices for detecting and measuring radioactive contamination and exposure, together with calculation methods and tools
				- management of radioactive waste
				- management of incidental and degraded situations
				- the methodology for analyzing workstations, supplemented by application to practical cases encountered in laboratories.
				In some chapters, concrete work situations are proposed to the reader who assumes the role of actor. In addition, the reader can check his understanding and acquisition of the concepts covered thanks to the "Take stock" sections that close the other parts of this volume.
				This book is an effective preparation for the knowledge test of the practical module and is an essential tool for obtaining the PCR certificate.
				The authors are experts in radiation protection, involved in the training of competent persons or even PCRs from the industrial and research sectors.`,
				author: 'Hugues Bruchet',
			},
			{
				extract: `The role of the competent person in radiation protection (PCR) has developed widely in recent years to occupy an essential function within establishments. Designated by the employer, the PCR must successfully complete a training course, the terms of which are defined by the order of December 6, 2013. This training, structured in two modules
				- theoretical and applied
				- is adapted to the importance of the radiological risk ("level" of training), to the nature of the activities concerned (sector) and possibly to the type of use of ionizing radiation sources (option).
				This volume is intended for PCRs or future PCRs involved in medical sector facilities.
				It will cover the different types of sources used: sealed radioactive sources (brachytherapy), unsealed radioactive sources (nuclear medicine), as well as electrical devices emitting ionizing radiation: X-ray generators used in conventional and dental radiology, scanners, gas pedals in radiotherapy, etc.
				It includes 9 chapters dealing with the following areas
				regulatory and practical aspects of radiation protection in medical facilities
				 - description of the different types of application of ionizing radiation in the medical sector: radiology, radiotherapy, brachytherapy and nuclear medicine
				 - the management of radioactive waste and effluents generated by some of these applications
				 - measurement of external exposure and detection, with an application to a concrete case of surface contamination
				 - the management of incidental and degraded situations in the medical environment
				 - the methodology of workstation analysis and risk assessment, supplemented by application to practical cases encountered in the medical sector: CT scanning, interventional radiology, brachytherapy and nuclear medicine.
				 Thanks to this new volume, the PCR working in the medical field will have all the information necessary to carry out his or her missions, from the acquisition of the regulatory notions to be respected to the calculation of protections, including an essential role in the implementation of workstation analyses.`,
				author: 'Hugues Bruchet, Amélie Roué et Christine Jimonet',
			},
			{
				extract: `This volume corresponds to the practical module dedicated to industrial and research facilities concerned with the possession or management of X-ray generators and sealed sources. In accordance with the regulatory requirements stipulating that this module must allow the application of theoretical training to concrete work situations that may be encountered, it includes 11 chapters dealing with the following aspects
				- a detailed overview of the application of these sources in industry and research
				- radiation protection in industrial and research facilities: the associated means of prevention, protection, training and detection
				- criteria for choosing detectors, measuring radioactive contamination and radiation leakage, and exposure, associated with methods for estimating dose rates and protective screens
				- management of incidental and degraded situations
				- the methodology of workstation analysis completed by practical case studies.
				This book is an effective preparation for the knowledge test of the practical module and is an essential tool for obtaining the PCR certificate.`,
				author: 'Jean-Claude Moreau and Marc Ammerich',
			},
			{
				extract:
					'It was time to retrace the history of nuclear physics. Bernard Fernandez takes you by the hand to guide you through the meanders of a complicated but fascinating science. Using ordinary French language, without scientific jargon or mathematical formulas, he addresses both the specialized readers, to whom he offers a historical perspective of their science, and the honest man, who wishes to be informed without having any particular scientific knowledge. In this lively account, well-known and lesser-known characters are mixed together, theories developed in enthusiasm and sometimes subsequently demolished, experimental protocols and detailed descriptions of instruments. One of the main ideas of the book is indeed that theory should never free itself from experimental reality.',
				author: 'Bernard Fernandez',
			},
			{
				extract:
					"Intended for a wide audience, Le monde subatomique describes the evolution of ideas about the interactions and constituents of matter, with their applications, from the discovery of the neutron to that of the Z° boson. It replaces the first volume, Approche élémentaire, of Luc Valentin's earlier work, Physique subatomique, a reference manual that is popular with teachers and students in France and abroad.",
				author: 'Luc Valentin',
			},
			{
				extract: `This book aims to synthesize many years of experience in the field of external dosimetry and protection techniques against this type of exposure in the industrial, research and medical fields. \n
				It is based on the theory related to the interaction of ionizing radiation with matter, empirical formulas, abacuses and illustrated by numerous numerical applications. In addition, it constantly refers to the state of the art, particularly in the field of calculation codes for external exposure and a number of recent medical and research projects. Furthermore, it compiles data scattered in numerous reference works, some of which are not readily available. \n
				This book is dedicated to professionals in radiation protection, dosimetry, and nuclear measurement, but it can also be used to complete the curriculum of students from technician to engineer level. \n
				This book is structured around two levels of reading: the first, which is accessible to all readers and for which elementary physics concepts leading to the understanding of phenomena related to external exposure are supported by simple numerical applications; the second, which is accessible at the end of each chapter and which details more complex points requiring non-trivial mathematical developments, if necessary. \n
				The first chapter deals with the definition of the fundamental radiometric and dosimetric quantities, allowing the interaction between radiation and matter to be approached from an angle dedicated to the deposition of the dose in biological tissues in the second chapter, to finally define and apply the protection and operational quantities related to radiation protection in the third chapter. \n
				In the following two chapters, particular emphasis is placed on the definition of risks and associated countermeasures (i.e. biological protection) inherent to the usual sources of radiation: radionuclides, X-ray generators, gas pedals (electrons, ions), etc., but also for more "exotic" devices, some of which are linked to expanding or future fields: power lasers, gas pedals, etc., for a range of energies that can be described as average (0 to 200 MeV).
				A chapter at the end of the book is entirely devoted to particle transport calculation codes using the Monte-Carlo method. The general principles are explained with a particular focus on the estimation of radiometric and dosimetric quantities described in the previous chapters. This part is also marked by numerical applications that clarify certain topics. It should be remembered that the computational codes whose algorithms exploit this method, constitute today reference tools for calculations related to dosimetry, radiation protection and radiophysics.`,
				author: 'Rodolphe Antoni et Laurent Bourgois',
			},
			{
				extract: `This book reviews the state of the art in dosimetric calculations, ionizing radiation metrology and radiation protection through problems related to concrete applications in the field. \n
				It proposes resolutions using analytical and semi-empirical formulas derived from the theory of nuclear physics and the latest research developments. For certain problems: cavity theory, calculation of absorbed doses for protons, calculation of quantities and dimensions around X-ray generators, the most recent data and calculational approaches are among the tools used. Moreover, in most of the proposed problems, an inter-comparison with numerical results from a Monte-Carlo type code is presented. The MCNP code, a worldwide used tool, has been chosen in this work to provide, when necessary, the "true values" in order to test the analytically or semi-empirically calculated results. For each case studied, the input files are provided in their entirety and their detailed architecture. Some complex geometries involved in the definition of the simulated radiological scenes are described as well as the functionalities used for particle transport monitoring. Furthermore, emphasis is put on the normalizations of the raw MCNP results and on the variance reduction techniques added to facilitate, or even allow, the convergence of the statistical estimators towards the final result. \n
				This book is intended for an audience with a solid foundation in the relevant fields and can be recommended for a physics degree level or above. It will bring theoretical and technical elements to engineers for computational services as well as to graduate students for their research work. Concerning the proposed pedagogical approach, each problem is independent with an increasing level of difficulty; the reader can thus study the problems that interest him in the order he wishes.`,
				author: 'Laurent Bourgois and Rodolphe Antoni',
			},
			{
				extract: `Radioactivity is everywhere, it surrounds us. Yet we have lived with it for several centuries without knowing it and it was only in 1896 that Henri Becquerel, Pierre and Marie Curie discovered it, giving us a glimpse of an unknown phenomenon capable of the worst as well as the best with various sources of radiation. \n
				Today, radioactivity is still perceived by the general public as a dangerous phenomenon. In reality, it is only dangerous in certain cases and its surveillance is even more essential. When and how to protect yourself from it? This is the role of a discipline called Radioprotection. \n
				From the creation of the first Commission on Radiation Protection to the latest regulations, this book highlights all aspects of the work of environment and human protection (detection equipment, measurements, screens, waste, etc.). \n
				A presentation of natural and artificial sources also shows us the extent of applications or uses requiring limited exposure of workers, patients or any other person. \n
				This book, without complex mathematical formulas, will allow all readers to better understand the role and the work of radiation protectionists and to no longer apprehend radioactivity !`,
				author: 'Marc Ammerich',
			},
			{
				extract:
					'These books are adapted to students in master radiation protection, engineering school but also to students specialized in BTS or license radiation protection. Its aim is to teach how to master the different cases proposed. The problems cover all topics from radioactivity, physical dosimetry, external and internal exposures, biological effects, detection, to regulatory aspects. These are nearly thirty years of teaching and designing exercises and problems that allow me to offer you this book',
				author: 'Marc Ammerich',
			},
		],
	},
	Manuals: {
		header: {
			title: 'Documentation',
			p: 'To help you to evaluate the possibilities offered by Dosimex-GX, you can download all the documentation associated with this code:',
			li: [
				'User manuals',
				'The validation files',
				'Some end of study internships reports using Dosimex',
			],
		},
		manuals: [
			'User manuals',
			'Gamma dose manual',
			'Generator X-ray manual',
			'Manual + Validation NF C15-160',
			'Practical values in radiology',
		],
		validations: [
			'Validation files and MCNP references',
			'Gamma emission validation file',
			'X-ray generator validation file',
			'X-ray generator reference MCNP/CEA',
			'MNCP/AREVA radionuclide reference',
			'X attenuation reference',
		],
		internships: [
			'End of study internships reports vs Dosimex',
			'Ulysse research papers',
			'Microshield vs Dosimex 1 research papers',
			'Microshield vs Dosimex 2 research papers',
			'Microshield vs Dosimex 3 research papers',
		],
	},
	Product: {
		buttonKnowMore: 'Read more',
		title: 'Product data sheet',
		descrip:
			'DOSIMEX 3.2 - Professional pack of 17 Excel tools for radiation protection. Complete radiation protection calculation solution, DOSIMEX brings together 17 professional codes developed in VBA/Excel, ready to use: 6 operational codes (dose calculations, zoning, protection), 6 interactive educational modules, 5 measurement and analysis utilities. Instant digital delivery • Single-user license • Support included',
		partE: {
			title: 'Pack content',
			p: [
				'All the codes and utilities (17) of the operational (6), learning (6) and measurement (5) packs presented on this site',
				'The associated documentation: user manual and validation file for each code',
				'Course documents (11): nuclear physics, nuclear measurement, charged particle MRI, photon MRI, neutron MRI, operational quantities, decision threshold: principles and application, statistics: principles, uncertainties, and hypothesis testing.',
				'Appendices (19) of the book "Calculation of doses generated by ionizing radiation" (EDP Sciences 2016).',
			],
		},
		between:
			'A general summary (SOMMAIRE_GENERAL.pps) at the root of the folders allows navigation through the entire Dosimex package.',
		prerequisites: {
			title: 'Prerequisites',
			p: 'The codes are written in VBA in Excel. The Dosimex package works with Windows XP to Windows 11 and Excel 2003 to 2024 by authorizing the operation of macros. On Mac and Linux it is necessary to create a "virtual machine".\n Depending on the security measures in place in your company, it is advisable to ask your IT department to whitelist Dosimex.',
			italic: '',
		},
		titlePrice: 'Get Dosimex 3.2 License',
		pricing: {
			title: 'Pricing',
			packageTitle: 'DOSIMEX 3.2 Pack - Single-user License',
			packageFeatures: [
				'Price: €500/year (excl. VAT)',
				'Annual license with updates included',
				'Technical support included',
				'Instant installation after purchase',
			],
			volumeTitle: 'Volume Discounts Available',
			volumeText: 'For purchasing multiple licenses, we offer preferential rates:',
			volumeItems: [
				'1-5 licenses: Request a quote',
				'6+ licenses: Custom enterprise pricing',
			],
			orderTitle: 'How to order?',
			orderText:
				'Request your personalized quote using the form below. We will respond promptly with your quote and payment terms.',
			quoteButton: 'Request a quote',
		},
		faq: {
			title: 'Frequently Asked Questions',
			questions: [
				{
					question: 'Why Excel?',
					answer: 'Excel is the standard working environment for professionals. No additional software to learn, easy integration into your existing workflows.',
				},
				{
					question: 'Which Excel version?',
					answer: 'Compatible with Excel 2003 to Excel 2024, from Windows XP to Windows 11. On Mac and Linux, a virtual machine is required.',
				},
				{
					question: 'Are updates included?',
					answer: 'Yes, all updates are included in your annual license, as well as technical support.',
				},
			],
		},
		questions: {
			title: 'A request for a quotation? Any questions?',
			p: 'Feel free to contact us via the form below or by phone at ',
		},
	},
	Training: {
		header: {
			title: 'Training',
			p: 'We offer on-site or videoconference intra-company training courses from 1 to 3 days to learn how to use Dosimex tools.\n These trainings are based on tutorials integrating the use of Dosimex tools in the broader framework of radiological risk analysis applied to concrete cases encountered in the industrial and medical world.',
		},
		section1: {
			title: 'Examples of topics covered, which can be modified according to the needs:',
			li: [
				'• Calculation of protection around medical and industrial X-ray generators',
				'• Application NF C 15-160',
				'• Management of a high activity Radium source',
				'• Technetium 99m syringe and operator protection',
				'• Fluorine 18 contamination',
				'• Co60, Ir192, Sr95, Cs137 gamma radiography',
				"• EDF's preferred radionuclides",
				'• ALARA approach on primary piping',
				'• Diffusion in a blockhouse baffle',
				'• Radiation protection around a fuel storage pool',
				'• Biological protection of a Californium 252 source (neutrons + gamma)',
				'• Food ionizations',
				'• High activity Strontium-Yttrium 90 source',
				'• Radiation protection analysis of a fission product waste package (CSDV)',
			],
		},
		section2: {
			title: 'In partnership with Veolia Nuclear Solutions, we offer other training courses on the following topics:',
			li: [
				'• Nuclear physics and radioactivity',
				'• Interaction between radiation and matter',
				'• Decision threshold (ISO 11929)',
				'• Gamma spectrometry',
			],
			button: 'Training catalogue',
		},
		questions: {
			title: 'Any questions ?',
			p: 'Feel free to contact us via the form below or by phone at 06 89 70 90 35',
			button: 'Contact us',
		},
	},
	Videos: {
		header: {
			title: 'Videos',
			p: 'You will find below all the videos concerning the operational, learning and measurement packages. We also propose on our YouTube channel other videos dedicated to nuclear physics, radioactivity, radiation-matter interaction, statistics and metrology...',
			button: 'Watch our YouTube channel',
		},
		packTitle: 'Videos from the pack ',
		packOpe: {
			name: 'operational',
			label: 'operational pack',
		},
		packPeda: {
			name: 'learning',
			label: 'learning pack',
		},
		packMes: {
			name: 'measurement',
			label: 'measurement pack',
		},
	},
	ContactForm: {
		title: 'Contact us',
		label: ['Name', 'Email', 'Phone', 'Company', 'Address', 'Subject', 'Message'],
		errorName: 'Please enter a name',
		errorEmail: ['Please enter an email', 'Please enter a valid email'],
		errorPhone: 'Please enter a valid phone number',
		errorMessage: 'Please enter a message',
		button: 'Send',
		sending: 'Sending...',
		messageSent: 'Message sent !',
		messageNotSent: 'Message not sent',
	},
	Footer: {
		col1: {
			p: [
				'Copyright © 2025 Designed by Dosimex',
				'All rights reserved ',
				'06 89 70 90 35',
				'Follow us on social media',
			],
		},
		col2: {
			title: 'Resources',
			p: ['Video archives', 'Manuals and validations', 'Readings'],
		},
		col3: {
			title: 'Company',
			p: ['About us', 'Legal', 'Contact'],
		},
	},
	Navbar: {
		items: ['Product', 'Training', 'Documentation', 'About us', 'Contact'],
		button: 'Get Dosimex',
	},
}

export default text
