name: tslint

on:
  push:
    branches: [ master, break/2.0 ]
  pull_request:
    branches: [ dev ]

jobs:
  tslinting:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: npm i
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'